import type { ContextualTip } from "./types"

export const contextualTips: ContextualTip[] = [
  {
    id: "admin-events-empty-hint",
    audiences: ["admin"],
    routePrefix: "/admin/dashboard/events",
    priority: 10,
    headline: "Events list",
    body: "Create events from this page or press ⌘N (Ctrl+N) while viewing events to jump to the create flow. Tie each event to a tour for cleaner reporting.",
    learnMoreArticleId: "tour-management",
    primaryAction: { label: "Create event", href: "/admin/dashboard/events/create" },
    snoozeDays: 14,
  },
  {
    id: "admin-tours-overview",
    audiences: ["admin"],
    routePrefix: "/admin/dashboard/tours",
    priority: 8,
    headline: "Tour routing",
    body: "Tours bundle dates, venues, and financial rollups. Start with a single tour even if you only have one show—it keeps logistics and ticketing aligned.",
    learnMoreArticleId: "tour-management",
    snoozeDays: 14,
  },
  {
    id: "venue-social-preview",
    audiences: ["venue"],
    routePrefix: "/venue/dashboard/social",
    priority: 9,
    headline: "Venue social",
    body: "Use this area for venue-specific announcements. Pair posts with dated events so followers see when doors open.",
    learnMoreArticleId: "venue-social-feed",
    snoozeDays: 10,
  },
  {
    id: "venue-documents",
    audiences: ["venue"],
    routePrefix: "/venue/dashboard/documents",
    priority: 9,
    headline: "Keep riders centralized",
    body: "Upload PDFs for insurance, hospitality, and stage plots so production teams pull one source of truth.",
    learnMoreArticleId: "venue-documents-equipment",
    snoozeDays: 14,
  },
  {
    id: "global-community",
    audiences: ["all"],
    routePrefix: "/community",
    priority: 5,
    headline: "Community tips",
    body: "Community shows network-wide posts. Use Discover to find new accounts, then follow them to personalize this feed.",
    learnMoreArticleId: "pulse-feed",
    snoozeDays: 21,
  },
]
