import type { OnboardingFormField, StaffOnboardingTemplate } from "@/types/onboarding-template-resolver"

const identityFields: OnboardingFormField[] = [
  {
    id: "legal_name",
    name: "legal_name",
    label: "Legal full name",
    type: "text",
    section: "Identity",
    order: 10,
    required: true,
    blocking: true,
    placeholder: "First Middle Last",
  },
  {
    id: "preferred_name",
    name: "preferred_name",
    label: "Preferred name",
    type: "text",
    section: "Identity",
    order: 20,
    required: false,
  },
  {
    id: "date_of_birth",
    name: "date_of_birth",
    label: "Date of birth",
    type: "date",
    section: "Identity",
    order: 30,
    required: true,
    blocking: true,
    validation: { minimumAge: 16 },
  },
]

const contactFields: OnboardingFormField[] = [
  {
    id: "phone",
    name: "phone",
    label: "Mobile phone",
    type: "phone",
    section: "Contact",
    order: 100,
    required: true,
    blocking: true,
  },
  {
    id: "address",
    name: "address",
    label: "Home address",
    type: "address",
    section: "Contact",
    order: 110,
    required: true,
    blocking: true,
  },
  {
    id: "emergency_contact",
    name: "emergency_contact",
    label: "Emergency contact",
    type: "emergency_contact",
    section: "Emergency Contact",
    order: 120,
    required: true,
    blocking: true,
  },
]

const commonComplianceFields: OnboardingFormField[] = [
  {
    id: "work_authorization",
    name: "work_authorization",
    label: "I am legally authorized to work for this engagement",
    type: "checkbox",
    section: "Work Eligibility",
    order: 200,
    required: true,
    blocking: true,
  },
  {
    id: "government_id",
    name: "government_id",
    label: "Government ID",
    type: "id_document",
    section: "Documents",
    order: 300,
    required: true,
    blocking: true,
    requiresAdminReview: true,
    credentialType: "government_id",
    validation: {
      fileTypes: ["image/jpeg", "image/png", "application/pdf"],
      maxFileSizeMb: 10,
    },
  },
  {
    id: "w9_or_tax_form",
    name: "w9_or_tax_form",
    label: "W-9 / tax form",
    type: "tax_info",
    section: "Tax / Payment",
    order: 400,
    required: true,
    blocking: true,
    requiresAdminReview: true,
    credentialType: "tax_form",
  },
  {
    id: "direct_deposit",
    name: "direct_deposit",
    label: "Payment information",
    type: "bank_info",
    section: "Tax / Payment",
    order: 410,
    required: false,
    blocking: false,
    requiresAdminReview: true,
    credentialType: "payment_info",
  },
  {
    id: "worker_waiver",
    name: "worker_waiver",
    label: "Worker agreement and event safety waiver",
    type: "waiver",
    section: "Waiver",
    order: 500,
    required: true,
    blocking: true,
  },
]

function withBaseFields(fields: OnboardingFormField[]): OnboardingFormField[] {
  return [...identityFields, ...contactFields, ...fields, ...commonComplianceFields]
}

export const DEFAULT_STAFF_ONBOARDING_TEMPLATES: StaffOnboardingTemplate[] = [
  {
    id: "default-general-staff",
    name: "General Staff",
    description: "Default onboarding for general event staff and contractors.",
    department: "General",
    position: "General Staff",
    employment_type: "contractor",
    fields: withBaseFields([]),
    estimated_days: 2,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["default", "general", "staff"],
    is_default: true,
  },
  {
    id: "default-security-guard",
    name: "Security Guard",
    description: "Compliance onboarding for licensed security staff.",
    department: "Security",
    position: "Security Guard",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "guard_card",
        name: "guard_card",
        label: "Guard card / security license",
        type: "file",
        section: "Certifications",
        order: 250,
        required: true,
        blocking: true,
        requiresAdminReview: true,
        credentialType: "guard_card",
        validation: {
          fileTypes: ["image/jpeg", "image/png", "application/pdf"],
          maxFileSizeMb: 10,
        },
      },
      {
        id: "de_escalation_acknowledgement",
        name: "de_escalation_acknowledgement",
        label: "I acknowledge the event de-escalation and safety expectations",
        type: "checkbox",
        section: "Training",
        order: 260,
        required: true,
        blocking: true,
      },
    ]),
    estimated_days: 3,
    required_documents: ["Government ID", "Guard card", "W-9 or tax form", "Worker waiver"],
    tags: ["security", "licensed", "compliance"],
    is_default: false,
  },
  {
    id: "default-bartender",
    name: "Bartender",
    description: "Onboarding for bar staff requiring age and alcohol service checks.",
    department: "Bar Staff",
    position: "Bartender",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "alcohol_server_permit",
        name: "alcohol_server_permit",
        label: "Alcohol server permit",
        type: "file",
        section: "Certifications",
        order: 250,
        required: true,
        blocking: true,
        requiresAdminReview: true,
        credentialType: "alcohol_server_permit",
        validation: {
          fileTypes: ["image/jpeg", "image/png", "application/pdf"],
          maxFileSizeMb: 10,
        },
      },
      {
        id: "over_21_confirmation",
        name: "over_21_confirmation",
        label: "I confirm I am 21 or older where required for this role",
        type: "checkbox",
        section: "Work Eligibility",
        order: 255,
        required: true,
        blocking: true,
      },
    ]),
    estimated_days: 2,
    required_documents: ["Government ID", "Alcohol server permit", "W-9 or tax form", "Worker waiver"],
    tags: ["bar", "service", "alcohol"],
    is_default: false,
  },
  {
    id: "default-street-team",
    name: "Street Team",
    description: "Lightweight onboarding for street team members and volunteers.",
    department: "Marketing",
    position: "Street Team",
    employment_type: "volunteer",
    fields: withBaseFields([
      {
        id: "shirt_size",
        name: "shirt_size",
        label: "Shirt size",
        type: "select",
        section: "Event Logistics",
        order: 230,
        required: true,
        options: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
      },
      {
        id: "zone_preference",
        name: "zone_preference",
        label: "Preferred zone or neighborhood",
        type: "text",
        section: "Event Logistics",
        order: 240,
        required: false,
      },
    ]),
    estimated_days: 1,
    required_documents: ["Government ID", "Worker waiver"],
    tags: ["street-team", "marketing", "volunteer"],
    is_default: false,
  },
  {
    id: "default-production-crew",
    name: "Production Crew",
    description: "Onboarding for production, stagehands, and operations crew.",
    department: "Production",
    position: "Production Crew",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "production_skills",
        name: "production_skills",
        label: "Production skills",
        type: "multiselect",
        section: "Experience",
        order: 230,
        required: true,
        options: ["Stagehand", "Audio", "Lighting", "Rigging", "Backline", "Forklift", "Site Ops", "Runner"],
      },
      {
        id: "osha_or_safety_cert",
        name: "osha_or_safety_cert",
        label: "OSHA or safety certification",
        type: "file",
        section: "Certifications",
        order: 250,
        required: false,
        requiresAdminReview: true,
        credentialType: "safety_certification",
        validation: {
          fileTypes: ["image/jpeg", "image/png", "application/pdf"],
          maxFileSizeMb: 10,
        },
      },
    ]),
    estimated_days: 2,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["production", "crew", "operations"],
    is_default: false,
  },
  {
    id: "default-foh-engineer",
    name: "FOH Engineer",
    description: "Onboarding for audio engineers and tour production specialists.",
    department: "Technical",
    position: "FOH Engineer",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "audio_experience_summary",
        name: "audio_experience_summary",
        label: "Audio experience summary",
        type: "textarea",
        section: "Experience",
        order: 230,
        required: true,
        blocking: true,
      },
      {
        id: "console_experience",
        name: "console_experience",
        label: "Console experience",
        type: "multiselect",
        section: "Experience",
        order: 240,
        required: false,
        options: ["Avid", "Yamaha", "DiGiCo", "Midas", "Allen & Heath", "Behringer", "Other"],
      },
    ]),
    estimated_days: 2,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["audio", "foh", "tour-crew"],
    is_default: false,
  },
  {
    id: "default-lighting-tech",
    name: "Lighting Tech",
    description: "Onboarding for lighting technicians and visual production crew.",
    department: "Technical",
    position: "Lighting Tech",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "lighting_experience_summary",
        name: "lighting_experience_summary",
        label: "Lighting experience summary",
        type: "textarea",
        section: "Experience",
        order: 230,
        required: true,
        blocking: true,
      },
      {
        id: "electrical_safety_acknowledgement",
        name: "electrical_safety_acknowledgement",
        label: "I acknowledge electrical and rigging safety expectations",
        type: "checkbox",
        section: "Training",
        order: 240,
        required: true,
        blocking: true,
      },
    ]),
    estimated_days: 2,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["lighting", "technical", "tour-crew"],
    is_default: false,
  },
  {
    id: "default-tour-manager",
    name: "Tour Manager",
    description: "Onboarding for tour managers and operational leads.",
    department: "Management",
    position: "Tour Manager",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "tour_management_experience",
        name: "tour_management_experience",
        label: "Tour management experience",
        type: "textarea",
        section: "Experience",
        order: 230,
        required: true,
        blocking: true,
      },
      {
        id: "driver_license",
        name: "driver_license",
        label: "Driver license",
        type: "id_document",
        section: "Documents",
        order: 240,
        required: false,
        requiresAdminReview: true,
        credentialType: "driver_license",
      },
    ]),
    estimated_days: 3,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["tour-manager", "management", "artist"],
    is_default: false,
  },
  {
    id: "default-merch-seller",
    name: "Merch Seller",
    description: "Onboarding for merch table staff and sellers.",
    department: "Merchandise",
    position: "Merch Seller",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "cash_handling_experience",
        name: "cash_handling_experience",
        label: "Cash handling experience",
        type: "textarea",
        section: "Experience",
        order: 230,
        required: false,
      },
      {
        id: "merch_settlement_acknowledgement",
        name: "merch_settlement_acknowledgement",
        label: "I understand merch settlement and inventory closeout requirements",
        type: "checkbox",
        section: "Training",
        order: 240,
        required: true,
        blocking: true,
      },
    ]),
    estimated_days: 1,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
    tags: ["merch", "seller", "artist"],
    is_default: false,
  },
  {
    id: "default-photo-video",
    name: "Photographer/Videographer",
    description: "Onboarding for media capture, event content, and tour documentation.",
    department: "Media",
    position: "Photographer/Videographer",
    employment_type: "contractor",
    fields: withBaseFields([
      {
        id: "portfolio_url",
        name: "portfolio_url",
        label: "Portfolio URL",
        type: "text",
        section: "Experience",
        order: 230,
        required: true,
        blocking: true,
      },
      {
        id: "media_release_acknowledgement",
        name: "media_release_acknowledgement",
        label: "I acknowledge media ownership, usage, and delivery requirements",
        type: "checkbox",
        section: "Waiver",
        order: 510,
        required: true,
        blocking: true,
      },
    ]),
    estimated_days: 2,
    required_documents: ["Government ID", "W-9 or tax form", "Worker waiver", "Media release"],
    tags: ["media", "photography", "videography"],
    is_default: false,
  },
]

export function getSafeFallbackOnboardingTemplate(): StaffOnboardingTemplate {
  const fallback = DEFAULT_STAFF_ONBOARDING_TEMPLATES.find((template) => template.id === "default-general-staff")

  if (!fallback) {
    return {
      id: "static-safe-fallback",
      name: "General Staff",
      description: "Safe fallback onboarding template used when no database template is available.",
      department: "General",
      position: "General Staff",
      employment_type: "contractor",
      fields: withBaseFields([]),
      estimated_days: 2,
      required_documents: ["Government ID", "W-9 or tax form", "Worker waiver"],
      tags: ["fallback"],
      is_default: true,
    }
  }

  return fallback
}
