import type { LucideIcon } from 'lucide-react'
import {
  Award,
  Banknote,
  Briefcase,
  Building,
  Calendar,
  CalendarCheck,
  CheckCircle,
  Clock,
  Crown,
  Disc3,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Lock,
  Megaphone,
  Mic,
  Music,
  Radio,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sliders,
  Star,
  Target,
  Ticket,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Volume2,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  award: Award,
  Award,
  banknote: Banknote,
  Banknote,
  briefcase: Briefcase,
  Briefcase,
  building: Building,
  Building,
  calendar: Calendar,
  Calendar,
  'calendar-check': CalendarCheck,
  CalendarCheck,
  'check-circle': CheckCircle,
  CheckCircle,
  clock: Clock,
  Clock,
  crown: Crown,
  Crown,
  disc3: Disc3,
  Disc3,
  globe: Globe,
  Globe,
  'graduation-cap': GraduationCap,
  GraduationCap,
  handshake: Handshake,
  Handshake,
  headphones: Headphones,
  Headphones,
  heart: Heart,
  Heart,
  lock: Lock,
  Lock,
  megaphone: Megaphone,
  Megaphone,
  mic: Mic,
  Mic,
  music: Music,
  Music,
  radio: Radio,
  Radio,
  send: Send,
  Send,
  settings: Settings,
  Settings,
  shield: Shield,
  Shield,
  'shield-check': ShieldCheck,
  ShieldCheck,
  sliders: Sliders,
  Sliders,
  star: Star,
  Star,
  target: Target,
  Target,
  ticket: Ticket,
  Ticket,
  'trending-up': TrendingUp,
  TrendingUp,
  trophy: Trophy,
  Trophy,
  'user-check': UserCheck,
  UserCheck,
  users: Users,
  Users,
  'volume-2': Volume2,
  Volume2,
  zap: Zap,
  Zap,
}

/** Resolve kebab-case or PascalCase catalog icon names to a Lucide component. */
export function resolveAchievementIcon(iconName?: string | null): LucideIcon {
  if (!iconName) return Trophy
  const key = iconName.trim()
  if (ICON_MAP[key]) return ICON_MAP[key]

  const pascal = key
    .split(/[-_\s]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  if (ICON_MAP[pascal]) return ICON_MAP[pascal]

  return Trophy
}

export { Trophy as FallbackAchievementIcon }
