import { defineLiveEventRole, type LiveEventRoleDefinition } from "@/lib/staff/live-event-role-catalog.types"

const credential = (
  key: string,
  label: string,
  options: Partial<LiveEventRoleDefinition["required_credentials"][number]> = {}
): LiveEventRoleDefinition["required_credentials"][number] => ({
  key,
  label,
  isRequired: options.isRequired ?? true,
  isExpiryTracked: options.isExpiryTracked ?? true,
  authority: options.authority,
  jurisdictionDependent: options.jurisdictionDependent,
})

export const LIVE_EVENT_ROLE_CATALOG_B: LiveEventRoleDefinition[] = [
  defineLiveEventRole({
    key: "lost-found-staff",
    label: "Lost + Found Staff",
    department: "Guest Services",
    role_category: "hospitality",
    employment_type: "part_time",
    job_summary: "Receives, catalogs, safeguards, and returns lost property through the event's approved process.",
    duties: ["Log found items accurately", "Secure items and process claimant verification", "Escalate high-value, sensitive, or hazardous items according to policy"],
    qualifications: ["Customer-service and detail-oriented operational experience preferred", "Discretion and accurate recordkeeping"],
    required_credentials: [],
    essentials: ["Chain-of-custody and retention policy", "Secure storage access", "Privacy-conscious claimant-verification process"],
    surfaces: ["guest_services", "inventory", "audit", "incident_reporting"],
    tags: ["lost-found", "guest-services"],
  }),
  defineLiveEventRole({
    key: "marketing-director",
    label: "Marketing Director",
    department: "Media & Marketing",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads event marketing strategy, channel planning, audience growth, and campaign performance.",
    duties: ["Set campaign strategy, budget, and channel priorities", "Coordinate creative, PR, social, paid media, and partnerships", "Review performance and reallocate resources within approved authority"],
    qualifications: ["Senior event, entertainment, or consumer-marketing experience", "Budget ownership, analytics, and cross-channel leadership skills"],
    required_credentials: [],
    essentials: ["Approved campaign goals and budget", "Access to channel analytics and approvals", "Brand, rights, and partner constraints"],
    surfaces: ["marketing", "analytics", "finance", "approvals", "content_calendar"],
    shiftBased: false,
    tags: ["marketing", "director"],
  }),
  defineLiveEventRole({
    key: "medic-team",
    label: "Medic Team",
    department: "Safety & Emergency",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Provides medical care within licensed scope and the event medical plan, coordinating with EMS as required.",
    duties: ["Staff assigned medical posts or response units", "Assess and treat patients within authorized scope", "Document care and coordinate escalation or transport with medical command"],
    qualifications: ["Current clinical qualification appropriate to assigned level and event plan", "Event or prehospital medical experience preferred"],
    required_credentials: [
      credential("clinical-license", "Current EMT/paramedic/nursing/medical license or certification appropriate to assigned scope", { authority: "Applicable licensing authority", jurisdictionDependent: true }),
      credential("cpr-bcls", "Current CPR/BLS credential appropriate to role", { authority: "Recognized training provider" }),
    ],
    essentials: ["Medical command structure and treatment/documentation system", "Required medical supplies and PPE", "Patient privacy and transfer-of-care procedure"],
    surfaces: ["medical", "incident_command", "incident_reporting", "scheduling"],
    tags: ["medical", "medic", "ems"],
  }),
  defineLiveEventRole({
    key: "merch-team",
    label: "Merch Team",
    department: "Merchandise",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Sells and manages approved artist or event merchandise and related inventory.",
    duties: ["Set up and operate assigned merchandise point", "Process sales and maintain inventory counts", "Reconcile stock and escalate discrepancies"],
    qualifications: ["Retail, merchandise, POS, or event-sales experience preferred", "Accuracy, guest service, and inventory-handling skills"],
    required_credentials: [],
    essentials: ["POS permissions and product catalog", "Inventory check-in/out process", "Finance reconciliation workflow"],
    surfaces: ["merchandise", "inventory", "finance", "scheduling"],
    tags: ["merch", "retail"],
  }),
  defineLiveEventRole({
    key: "mobile-app-team",
    label: "Mobile App Team",
    department: "Data & Technology",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Builds or supports the event mobile application, operational content, and live-service integrations.",
    duties: ["Maintain assigned app features or content", "Monitor production issues and release approved updates", "Coordinate data feeds, notifications, and support escalation"],
    qualifications: ["Mobile product, engineering, QA, or content-operations experience relevant to assignment", "Knowledge of release management, analytics, and incident response"],
    required_credentials: [],
    essentials: ["Production access under least privilege", "Release and rollback procedure", "Issue tracker and on-call escalation"],
    surfaces: ["product", "analytics", "tasks", "incident_reporting"],
    shiftBased: false,
    tags: ["mobile-app", "technology"],
  }),
  defineLiveEventRole({
    key: "paid-ads-team",
    label: "Paid Ads Team",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Plans, launches, and optimizes approved paid-media campaigns for event goals.",
    duties: ["Build and manage approved campaigns", "Monitor spend, pacing, and performance", "Report results and recommend optimizations"],
    qualifications: ["Hands-on paid-media buying experience on relevant platforms", "Strong analytics, budget-control, and creative-testing skills"],
    required_credentials: [],
    essentials: ["Approved budgets and account access", "Tracking and attribution configuration", "Creative and legal approval workflow"],
    surfaces: ["marketing", "analytics", "finance", "approvals"],
    shiftBased: false,
    tags: ["paid-media", "ads"],
  }),
  defineLiveEventRole({
    key: "parking-staff",
    label: "Parking Staff",
    department: "Transportation",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Directs vehicles and guests within approved parking areas and traffic plans.",
    duties: ["Guide vehicles to assigned areas", "Maintain lanes, accessible spaces, and emergency routes", "Report congestion, incidents, or unsafe conditions"],
    qualifications: ["Parking, traffic, guest-service, or event-operations experience preferred", "Clear communication and situational awareness"],
    required_credentials: [],
    essentials: ["Current parking/traffic plan", "High-visibility PPE where required", "Radio and escalation access"],
    surfaces: ["transportation", "site_operations", "scheduling", "incident_reporting"],
    tags: ["parking", "traffic"],
  }),
  defineLiveEventRole({
    key: "partnerships-sponsors-team",
    label: "Partnerships + Sponsors Team",
    department: "Partnerships",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Manages sponsor relationships, contractual deliverables, and on-site partner execution.",
    duties: ["Track sponsor obligations and deadlines", "Coordinate activation needs across production, marketing, and operations", "Document delivery and resolve partner issues"],
    qualifications: ["Sponsorship, partnerships, account-management, or experiential-marketing experience", "Contract/detail tracking and stakeholder-management skills"],
    required_credentials: [],
    essentials: ["Current sponsor agreements and deliverables matrix", "Approval authority and change log", "Proof-of-performance workflow"],
    surfaces: ["sponsor_deliverables", "crm", "contracts", "approvals"],
    shiftBased: false,
    tags: ["sponsorship", "partnerships"],
  }),
  defineLiveEventRole({
    key: "permits-coordinator",
    label: "Permits Coordinator",
    department: "Compliance",
    role_category: "operations",
    employment_type: "contractor",
    job_summary: "Tracks event permits, inspections, deadlines, and agency requirements.",
    duties: ["Maintain permit register and submission schedule", "Coordinate supporting documents and inspections", "Escalate conditions, deficiencies, or deadline risks"],
    qualifications: ["Event permitting, production, municipal-coordination, or compliance experience", "Strong documentation and deadline management"],
    required_credentials: [],
    essentials: ["Authoritative permit register", "Agency contacts and inspection schedule", "Document storage and expiration alerts"],
    surfaces: ["permits", "compliance", "calendar", "documents"],
    shiftBased: false,
    tags: ["permits", "compliance"],
  }),
  defineLiveEventRole({
    key: "photographer",
    label: "Photographer",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Captures approved still photography for event, artist, editorial, or sponsor needs.",
    duties: ["Photograph assigned subjects and moments", "Follow access, flash, pit, rights, and sponsor guidelines", "Deliver edited or selects-based assets through the approved media workflow"],
    qualifications: ["Professional event/concert photography portfolio appropriate to assignment", "Reliable file management and fast-turnaround capability where required"],
    required_credentials: [],
    essentials: ["Photo credential/access rules", "Approved shot list and rights guidance", "File-delivery, metadata, and retention workflow"],
    surfaces: ["media_library", "credentials", "content_calendar", "approvals"],
    tags: ["photo", "media"],
  }),
  defineLiveEventRole({
    key: "production-manager",
    label: "Production Manager",
    department: "Production",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads technical and operational production delivery across departments, vendors, and show schedules.",
    duties: ["Own production planning and day-of coordination", "Manage technical vendors, schedules, changes, and escalations", "Maintain production readiness, safety coordination, and cross-department handoffs"],
    qualifications: ["Senior live-event production-management experience", "Strong budgeting, advancing, scheduling, and technical-coordination skills"],
    required_credentials: [],
    essentials: ["Master production schedule and run of show", "Vendor, equipment, and budget visibility", "Authority matrix and incident escalation"],
    surfaces: ["advancing", "run_of_show", "scheduling", "vendors", "finance", "incident_reporting"],
    tags: ["production", "management"],
  }),
  defineLiveEventRole({
    key: "public-relations-team",
    label: "Public Relations Team",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Manages media relations, announcements, press materials, and reputation communications.",
    duties: ["Draft and distribute approved press materials", "Manage media outreach, requests, and interview coordination", "Monitor coverage and route sensitive issues for approval"],
    qualifications: ["PR, communications, journalism, or entertainment-publicity experience", "Strong writing, media-relations, and judgment skills"],
    required_credentials: [],
    essentials: ["Approved messaging and spokesperson list", "Media/contact database", "Crisis and approval escalation path"],
    surfaces: ["press", "crm", "approvals", "media_monitoring"],
    shiftBased: false,
    tags: ["pr", "press", "public-relations"],
  }),
  defineLiveEventRole({
    key: "pyro-technician",
    label: "Pyro Technician",
    department: "Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Supports licensed pyrotechnic or special-effects operations only within approved permits, plans, and qualified supervision.",
    duties: ["Perform assigned pyrotechnic/special-effects duties within licensed scope", "Complete required safety and coordination checks before operation", "Stop and escalate any unsafe or out-of-scope condition"],
    qualifications: ["Documented professional pyrotechnic/special-effects experience appropriate to assignment", "Knowledge of applicable fire, venue, and permitting requirements"],
    required_credentials: [credential("pyro-license", "Pyrotechnic / special-effects operator credential required by jurisdiction", { authority: "Applicable fire/licensing authority", jurisdictionDependent: true })],
    essentials: ["Approved permit and effects plan", "Qualified chain of command and exclusion-zone controls", "Fire/safety coordination and emergency-stop authority"],
    surfaces: ["permits", "run_of_show", "incident_command", "incident_reporting"],
    tags: ["pyro", "special-effects"],
  }),
  defineLiveEventRole({
    key: "rigging-crew",
    label: "Rigging Crew",
    department: "Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Installs, inspects, and supports approved entertainment-rigging systems within assigned qualifications and engineered plans.",
    duties: ["Perform assigned rigging work to approved plans and supervision", "Inspect assigned rigging components and report concerns", "Coordinate lifts, access, and changes with production leadership"],
    qualifications: ["Professional entertainment-rigging experience appropriate to assigned work", "Knowledge of fall protection, load handling, and venue rigging rules"],
    required_credentials: [
      credential("rigging-qualification", "Recognized rigging qualification/certification where required", { isRequired: false, jurisdictionDependent: true }),
      credential("fall-protection", "Fall-protection training where exposed to fall hazards", { isExpiryTracked: false, jurisdictionDependent: true }),
    ],
    essentials: ["Approved rigging plot/engineering documentation", "Required PPE and fall-protection system", "Clear lift-command and stop-work protocol"],
    surfaces: ["equipment", "run_of_show", "scheduling", "incident_reporting"],
    tags: ["rigging", "production"],
  }),
  defineLiveEventRole({
    key: "runner-team",
    label: "Runner Team",
    department: "Production",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Handles time-sensitive authorized errands, pickups, and deliveries supporting artists and production.",
    duties: ["Complete assigned runs and deliveries", "Track receipts/items and status updates", "Escalate delays, access, or transportation issues"],
    qualifications: ["Reliable driving and local-navigation experience preferred", "Professional discretion and responsiveness"],
    required_credentials: [credential("driver-license", "Valid driver license when driving is assigned", { jurisdictionDependent: true })],
    essentials: ["Dispatch contact and authorized spending limits", "Vehicle assignment when required", "Receipt and chain-of-custody workflow"],
    surfaces: ["dispatch", "transportation", "tasks", "finance"],
    tags: ["runner", "production"],
  }),
  defineLiveEventRole({
    key: "security-director",
    label: "Security Director",
    department: "Security",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads event security planning, staffing, command, and coordination with venue and public-safety partners.",
    duties: ["Develop and execute the approved security plan", "Lead security supervisors and coordinate incidents", "Align access, crowd, emergency, and agency interfaces"],
    qualifications: ["Senior event-security or public-safety leadership experience", "Strong incident-command, staffing, and risk-management capability"],
    required_credentials: [credential("security-manager-license", "Security manager/guard credential where required by jurisdiction", { jurisdictionDependent: true })],
    essentials: ["Approved security and emergency plans", "Command communications and incident log", "Clear agency coordination and escalation authority"],
    surfaces: ["security", "incident_command", "credentials", "incident_reporting"],
    tags: ["security", "director"],
  }),
  defineLiveEventRole({
    key: "security-guard",
    label: "Security Guard",
    department: "Security",
    role_category: "security",
    employment_type: "part_time",
    job_summary: "Provides assigned security, access, and safety functions under the event security plan.",
    duties: ["Staff assigned post or patrol", "Enforce approved access and safety policies within role scope", "Report and escalate incidents or hazards"],
    qualifications: ["Event-security experience preferred and any legally required eligibility", "De-escalation, observation, and communication skills"],
    required_credentials: [credential("guard-card", "Security guard license/card where required", { authority: "Applicable licensing authority", jurisdictionDependent: true })],
    essentials: ["Post orders and escalation chain", "Radio/communications access where assigned", "Required credential and uniform/PPE"],
    surfaces: ["security", "credentials", "scheduling", "incident_reporting"],
    tags: ["security", "guard"],
  }),
  defineLiveEventRole({
    key: "set-designer",
    label: "Set Designer",
    department: "Creative Production",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Designs scenic environments and set elements that support the event or performance concept.",
    duties: ["Develop scenic concepts and production documentation", "Coordinate materials, fabrication, and installation constraints", "Review changes with creative and production leadership"],
    qualifications: ["Professional scenic/set-design experience and portfolio", "Knowledge of fabrication, materials, and production documentation"],
    required_credentials: [],
    essentials: ["Approved creative brief and dimensions", "Budget and production constraints", "Review and change-approval workflow"],
    surfaces: ["creative", "approvals", "vendors", "tasks"],
    shiftBased: false,
    tags: ["set-design", "scenic"],
  }),
  defineLiveEventRole({
    key: "shuttle-driver",
    label: "Shuttle Driver",
    department: "Transportation",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Transports approved passengers on scheduled event shuttle routes using assigned vehicles.",
    duties: ["Operate assigned shuttle safely on approved route", "Complete required pre/post-trip checks", "Coordinate timing and incidents with dispatch"],
    qualifications: ["Appropriate driving experience and eligibility for assigned vehicle", "Customer-service and route-management skills"],
    required_credentials: [
      credential("driver-license", "Driver license/class required for assigned vehicle", { jurisdictionDependent: true }),
      credential("passenger-endorsement", "Passenger/commercial endorsement where required", { isRequired: false, jurisdictionDependent: true }),
    ],
    essentials: ["Approved route and dispatch schedule", "Vehicle inspection/reporting workflow", "Hours-of-service and accessibility procedures where applicable"],
    surfaces: ["transportation", "dispatch", "equipment", "incident_reporting"],
    tags: ["shuttle", "driver"],
  }),
  defineLiveEventRole({
    key: "site-operations-manager",
    label: "Site Operations Manager",
    department: "Site Operations",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads site readiness and day-of infrastructure operations across public, back-of-house, and service areas.",
    duties: ["Coordinate site build, maintenance, and operational readiness", "Lead issue resolution across fencing, sanitation, roads, utilities, and guest infrastructure", "Track site changes, hazards, and handoffs"],
    qualifications: ["Senior festival/site/facilities-operations experience", "Strong vendor, schedule, and incident-management skills"],
    required_credentials: [],
    essentials: ["Master site plan and change log", "Vendor and infrastructure contacts", "Authority and escalation matrix"],
    surfaces: ["site_operations", "vendors", "scheduling", "tasks", "incident_reporting"],
    tags: ["site-operations", "management"],
  }),
  defineLiveEventRole({
    key: "social-media-team",
    label: "Social Media Team",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Plans, publishes, and monitors approved social content and audience engagement.",
    duties: ["Publish scheduled and real-time approved content", "Monitor comments, messages, and emerging issues", "Coordinate content capture, approvals, and escalation"],
    qualifications: ["Professional social-media/content experience", "Platform fluency, writing skill, and fast judgment under live-event conditions"],
    required_credentials: [],
    essentials: ["Approved content calendar and account access", "Moderation/escalation guidance", "Rights and sponsor requirements"],
    surfaces: ["content_calendar", "media_library", "approvals", "analytics"],
    tags: ["social-media", "content"],
  }),
  defineLiveEventRole({
    key: "stage-manager",
    label: "Stage Manager",
    department: "Production",
    role_category: "production",
    employment_type: "contractor",
    job_summary: "Runs stage-level timing, cueing, communication, and handoffs according to the show schedule.",
    duties: ["Maintain stage schedule and cue flow", "Coordinate artists, stagehands, audio, lighting, and production", "Escalate delays, safety issues, or show-impacting changes"],
    qualifications: ["Professional stage-management or live-production experience", "Strong cueing, radio discipline, and schedule management"],
    required_credentials: [],
    essentials: ["Current run of show and stage plot", "Command communication channel", "Defined show-stop and escalation authority"],
    surfaces: ["run_of_show", "scheduling", "tasks", "incident_reporting"],
    tags: ["stage", "management"],
  }),
  defineLiveEventRole({
    key: "stagehand",
    label: "Stagehand",
    department: "Production",
    role_category: "technical",
    employment_type: "part_time",
    job_summary: "Supports event load-in, setup, changeovers, show operations, and load-out under department supervision.",
    duties: ["Perform assigned setup, movement, and strike tasks", "Support approved stage/equipment changes", "Follow safety, PPE, and supervisor instructions"],
    qualifications: ["Stagehand, production-labor, or related experience preferred", "Ability to work safely in a team around event equipment"],
    required_credentials: [credential("site-safety", "Event/site safety orientation", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Call time and department assignment", "Required PPE and tools", "Task lead and stop-work/escalation path"],
    surfaces: ["scheduling", "tasks", "equipment", "incident_reporting"],
    tags: ["stagehand", "production-labor"],
  }),
  defineLiveEventRole({
    key: "sustainability-team",
    label: "Sustainability Team",
    department: "Sustainability",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Implements event sustainability programs for waste, materials, water, energy, and guest education.",
    duties: ["Operate assigned sustainability stations or audits", "Track waste/material-diversion data", "Coordinate issues and improvements with site and vendor teams"],
    qualifications: ["Sustainability, waste-operations, environmental-programs, or event experience preferred", "Good data-collection and guest-communication skills"],
    required_credentials: [],
    essentials: ["Approved sustainability plan and metrics", "Waste-stream and vendor guidance", "Data-capture and reporting workflow"],
    surfaces: ["sustainability", "analytics", "site_operations", "vendors"],
    tags: ["sustainability", "environment"],
  }),
  defineLiveEventRole({
    key: "talent-buyer",
    label: "Talent Buyer",
    department: "Talent & Booking",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Sources, evaluates, and contracts artists within programming, budget, and schedule strategy.",
    duties: ["Develop talent targets and offers", "Negotiate within authorized commercial terms", "Coordinate contracts, holds, and handoff to advancing/production"],
    qualifications: ["Professional talent-buying, booking, or artist-management experience", "Market knowledge, negotiation, and budget-management skills"],
    required_credentials: [],
    essentials: ["Programming strategy and approved budget", "Offer, hold, and contract tracking", "Approval thresholds and conflict checks"],
    surfaces: ["crm", "contracts", "finance", "advancing", "calendar"],
    shiftBased: false,
    tags: ["talent", "booking"],
  }),
  defineLiveEventRole({
    key: "ticketing-manager",
    label: "Ticketing Manager",
    department: "Ticketing",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads ticketing setup, inventory, reporting, access-control integration, and customer-service policy.",
    duties: ["Configure and monitor approved ticket inventory", "Coordinate onsale, comps, holds, access control, and reporting", "Resolve escalated ticketing issues and reconcile data"],
    qualifications: ["Professional ticketing/event-commerce experience", "Strong inventory, reporting, and systems-integration skills"],
    required_credentials: [],
    essentials: ["Ticketing-platform admin access", "Inventory and comp-approval rules", "Fraud, refund, and escalation procedures"],
    surfaces: ["ticketing", "analytics", "finance", "access_control"],
    tags: ["ticketing", "management"],
  }),
  defineLiveEventRole({
    key: "traffic-control-team",
    label: "Traffic Control Team",
    department: "Transportation",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Supports vehicle and pedestrian traffic movements according to the approved traffic-management plan.",
    duties: ["Staff assigned traffic-control points", "Direct movements within approved role and plan", "Report congestion, hazards, or plan deviations"],
    qualifications: ["Traffic, parking, event, or roadway-operations experience appropriate to assignment", "Clear communication and situational awareness"],
    required_credentials: [credential("traffic-control", "Traffic-control / flagger certification where required", { isRequired: false, jurisdictionDependent: true })],
    essentials: ["Approved traffic plan and post assignment", "High-visibility PPE and communications", "Emergency-vehicle and accessible-route priorities"],
    surfaces: ["transportation", "site_operations", "scheduling", "incident_reporting"],
    tags: ["traffic", "transportation"],
  }),
  defineLiveEventRole({
    key: "tour-manager",
    label: "Tour Manager",
    department: "Tour Management",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Coordinates the touring party's day-to-day schedule, travel, finances, advancing, and operational communication.",
    duties: ["Maintain master tour itinerary and daily schedule", "Coordinate venues, travel, lodging, crew, settlements, and artist needs", "Manage changes and communicate decisions across the touring party"],
    qualifications: ["Professional touring or live-event-management experience", "Strong advancing, budgeting, scheduling, and people-management skills"],
    required_credentials: [],
    essentials: ["Master itinerary and contact sheet", "Travel/finance authority matrix", "Daily reporting and change log"],
    surfaces: ["touring", "advancing", "travel", "finance", "scheduling"],
    tags: ["touring", "tour-manager"],
  }),
  defineLiveEventRole({
    key: "transportation-coordinator",
    label: "Transportation Coordinator",
    department: "Transportation",
    role_category: "operations",
    employment_type: "contractor",
    job_summary: "Plans and dispatches approved vehicles, drivers, routes, and movement schedules.",
    duties: ["Build and maintain transportation schedule", "Dispatch vehicles and track status", "Coordinate route, access, and delay issues with logistics and site teams"],
    qualifications: ["Event transportation, dispatch, logistics, or fleet experience", "Strong scheduling, mapping, and communication skills"],
    required_credentials: [],
    essentials: ["Vehicle/driver roster and route plan", "Dispatch communications", "Incident, delay, and maintenance workflow"],
    surfaces: ["transportation", "dispatch", "scheduling", "equipment"],
    tags: ["transportation", "dispatch"],
  }),
  defineLiveEventRole({
    key: "trash-recycling-team",
    label: "Trash + Recycling Team",
    department: "Sustainability",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Collects and sorts event waste according to approved sanitation and diversion procedures.",
    duties: ["Service assigned waste/recycling stations", "Separate materials according to program rules", "Report contamination, overflow, or hazardous items"],
    qualifications: ["Waste, sanitation, custodial, or event-operations experience preferred", "Ability to follow PPE and material-handling procedures"],
    required_credentials: [],
    essentials: ["Waste-stream guidance and route plan", "PPE and approved handling tools", "Hazardous-item escalation procedure"],
    surfaces: ["sustainability", "site_operations", "tasks", "incident_reporting"],
    tags: ["recycling", "waste"],
  }),
  defineLiveEventRole({
    key: "vendor-coordinator",
    label: "Vendor Coordinator",
    department: "Vendors",
    role_category: "operations",
    employment_type: "contractor",
    job_summary: "Coordinates vendor onboarding, arrival, compliance, placement, and day-of support.",
    duties: ["Maintain vendor roster, requirements, and schedules", "Coordinate load-in, credentials, permits, and utilities", "Resolve or escalate vendor operational issues"],
    qualifications: ["Event-vendor management, operations, or account-coordination experience", "Strong documentation and stakeholder communication"],
    required_credentials: [],
    essentials: ["Vendor agreements and contact roster", "Permit/credential status visibility", "Load-in and issue-tracking workflow"],
    surfaces: ["vendors", "permits", "credentials", "scheduling"],
    tags: ["vendor", "coordination"],
  }),
  defineLiveEventRole({
    key: "videographer",
    label: "Videographer",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Captures approved video content for event, artist, editorial, or sponsor deliverables.",
    duties: ["Film assigned performances, interviews, or event moments", "Follow access, rights, and production guidelines", "Deliver organized footage and metadata through the approved media workflow"],
    qualifications: ["Professional event/video-production portfolio", "Camera, audio-capture, and file-management skills appropriate to assignment"],
    required_credentials: [],
    essentials: ["Approved shot list and access", "Rights/release and embargo guidance", "File ingest, backup, and delivery process"],
    surfaces: ["media_library", "credentials", "content_calendar", "approvals"],
    tags: ["video", "media"],
  }),
  defineLiveEventRole({
    key: "vip-experience-team",
    label: "VIP Experience Team",
    department: "Hospitality",
    role_category: "hospitality",
    employment_type: "part_time",
    job_summary: "Delivers premium guest services and manages designated VIP spaces and benefits.",
    duties: ["Welcome and assist VIP guests", "Operate check-in, amenity, and service workflows", "Coordinate issues with hospitality, security, and ticketing"],
    qualifications: ["Premium hospitality, guest-services, or event experience preferred", "Professional, discreet, and proactive service skills"],
    required_credentials: [],
    essentials: ["VIP entitlement list and access rules", "Service standards and escalation contacts", "Guest privacy expectations"],
    surfaces: ["guest_services", "credentials", "ticketing", "scheduling"],
    tags: ["vip", "hospitality"],
  }),
  defineLiveEventRole({
    key: "volunteer-coordinator",
    label: "Volunteer Coordinator",
    department: "Workforce",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Recruits, schedules, briefs, and supports event volunteers across approved assignments.",
    duties: ["Maintain volunteer roster and shift assignments", "Deliver orientation and role information", "Track attendance, issues, and reassignment needs"],
    qualifications: ["Volunteer-management, staffing, nonprofit, or event experience", "Strong scheduling, communication, and people-support skills"],
    required_credentials: [],
    essentials: ["Volunteer role catalog and schedules", "Check-in and communication workflow", "Escalation path for safety or performance issues"],
    surfaces: ["workforce", "scheduling", "onboarding", "timekeeping"],
    tags: ["volunteer", "workforce"],
  }),
  defineLiveEventRole({
    key: "water-station-staff",
    label: "Water Station Staff",
    department: "Guest Services",
    role_category: "hospitality",
    employment_type: "part_time",
    job_summary: "Operates approved hydration stations and helps maintain safe, clean water-service areas.",
    duties: ["Set up, monitor, and restock assigned water station", "Maintain cleanliness and queue flow", "Report supply, sanitation, or equipment issues"],
    qualifications: ["Guest-service or event-operations experience preferred", "Ability to follow sanitation and service procedures"],
    required_credentials: [credential("food-handler", "Food/water-service credential where required by jurisdiction", { isRequired: false, jurisdictionDependent: true })],
    essentials: ["Approved potable-water source and sanitation procedure", "Supply and restock plan", "Issue-escalation contact"],
    surfaces: ["guest_services", "inventory", "site_operations", "incident_reporting"],
    tags: ["water", "hydration"],
  }),
  defineLiveEventRole({
    key: "weather-monitoring-team",
    label: "Weather Monitoring Team",
    department: "Safety & Emergency",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Monitors authoritative weather information and communicates decision-support updates to event leadership.",
    duties: ["Monitor approved weather sources and thresholds", "Issue timely observations to authorized decision-makers", "Maintain a log of alerts, conditions, and communications"],
    qualifications: ["Meteorology, weather-operations, emergency-management, or trained event-weather monitoring experience", "Ability to interpret approved forecast/alert sources and follow escalation thresholds"],
    required_credentials: [],
    essentials: ["Authoritative weather sources and event thresholds", "Direct communications to incident command/event leadership", "Timestamped alert and decision log"],
    surfaces: ["weather", "incident_command", "audit", "site_operations"],
    tags: ["weather", "safety"],
  }),
  defineLiveEventRole({
    key: "wristband-credential-printing",
    label: "Wristband + Credential Printing",
    department: "Access & Credentials",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Produces, controls, and distributes approved wristbands, badges, and credential media.",
    duties: ["Print and prepare authorized credential batches", "Maintain inventory and reconciliation records", "Secure blank stock and escalate discrepancies or reprint requests"],
    qualifications: ["Credential-production, print-operations, registration, or inventory experience preferred", "High accuracy and chain-of-custody awareness"],
    required_credentials: [],
    essentials: ["Authorized print queue and access matrix", "Secure stock and inventory controls", "Reprint, void, and reconciliation audit trail"],
    surfaces: ["credentials", "inventory", "audit", "access_control"],
    tags: ["wristband", "credential-printing"],
  }),
]
