import { defineLiveEventRole, type LiveEventRoleDefinition } from "@/lib/staff/live-event-role-catalog.types"

const credential = (
  key: string,
  label: string,
  options: Partial<LiveEventRoleDefinition["required_credentials"][number]> = {}
): LiveEventRoleDefinition["required_credentials"][number] => ({
  key,
  label,
  isRequired: options.isRequired ?? true,
  isExpiryTracked: options.isExpiryTracked ?? true,
  authority: options.authority,
  jurisdictionDependent: options.jurisdictionDependent,
})

export const LIVE_EVENT_ROLE_CATALOG_A: LiveEventRoleDefinition[] = [
  defineLiveEventRole({
    key: "ada-accessibility-team",
    label: "ADA Accessibility Team",
    department: "Guest Services",
    role_category: "hospitality",
    employment_type: "part_time",
    job_summary: "Coordinates accessibility services so guests with disabilities can navigate and participate in the event.",
    duties: ["Support accessible entry, seating, viewing, transportation, and service requests", "Coordinate accommodations with guest services, security, medical, and site operations", "Document accessibility issues and escalate unresolved barriers"],
    qualifications: ["Guest services, accessibility, disability-services, or event-operations experience preferred", "Respectful communication, discretion, and problem-solving skills"],
    required_credentials: [credential("accessibility-training", "Accessibility / disability inclusion training", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Know the event accessibility plan and escalation contacts", "Protect guest privacy and dignity", "Maintain reliable communications while assigned"],
    surfaces: ["guest_services", "site_operations", "scheduling", "incident_reporting"],
    tags: ["accessibility", "ada"],
  }),
  defineLiveEventRole({
    key: "artist-hospitality",
    label: "Artist Hospitality",
    department: "Artist Services",
    role_category: "hospitality",
    employment_type: "contractor",
    job_summary: "Supports artists and touring parties with dressing rooms, hospitality, meals, arrivals, and day-of needs.",
    duties: ["Prepare and maintain artist hospitality areas", "Coordinate hospitality-rider needs with catering and production", "Track artist arrivals, requests, and department handoffs"],
    qualifications: ["Live-event, hospitality, or artist-services experience preferred", "Professional discretion and calm guest-facing communication"],
    required_credentials: [],
    essentials: ["Current artist schedule and hospitality rider access", "Clear escalation path to artist relations or production", "Confidential handling of artist information"],
    surfaces: ["advancing", "catering", "scheduling", "tasks"],
    tags: ["artist-services", "hospitality"],
  }),
  defineLiveEventRole({
    key: "artist-relations-manager",
    label: "Artist Relations Manager",
    department: "Artist Services",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Owns the day-of relationship between the event and artists, managers, and touring teams.",
    duties: ["Serve as primary artist-facing contact", "Coordinate arrivals, credentials, hospitality, schedule changes, and issue resolution", "Maintain handoffs with production, talent buying, security, and transportation"],
    qualifications: ["Several years of artist-relations, touring, venue, or festival-operations experience", "Strong conflict-resolution, scheduling, and stakeholder-management skills"],
    required_credentials: [],
    essentials: ["Access to artist contacts, schedules, riders, and escalation tree", "Authority to coordinate cross-department resolutions", "Accurate confidential handoffs"],
    surfaces: ["advancing", "credentials", "scheduling", "transportation", "tasks"],
    tags: ["artist-services", "artist-relations"],
  }),
  defineLiveEventRole({
    key: "audio-engineer",
    label: "Audio Engineer",
    department: "Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Operates and supports live-audio systems to deliver safe, intelligible, artist-appropriate sound.",
    duties: ["Prepare and operate assigned audio systems", "Coordinate line checks, sound checks, and show cues with stage and artist teams", "Report equipment, signal, or safety issues to production leadership"],
    qualifications: ["Professional live-sound experience appropriate to the system and show scale", "Working knowledge of signal flow, consoles, RF/audio coordination, and safe production practices"],
    required_credentials: [credential("audio-safety", "Live audio / electrical safety training", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Approved system and show-file access where applicable", "Required PPE and hearing protection", "Clear cueing and communications path"],
    surfaces: ["run_of_show", "equipment", "scheduling", "incident_reporting"],
    tags: ["audio", "sound", "production"],
  }),
  defineLiveEventRole({
    key: "backstage-coordinator",
    label: "Backstage Coordinator",
    department: "Production",
    role_category: "production",
    employment_type: "part_time",
    job_summary: "Coordinates backstage movement, access, readiness, and communication around performance areas.",
    duties: ["Maintain backstage readiness and approved access flow", "Coordinate artist, crew, and vendor movement with stage management and security", "Track backstage requests, deliveries, and handoffs"],
    qualifications: ["Backstage, venue, stage, or festival-operations experience preferred", "Strong radio discipline and situational awareness"],
    required_credentials: [],
    essentials: ["Current backstage access list and schedule", "Radio access and escalation contact", "Understanding of restricted areas and credential rules"],
    surfaces: ["credentials", "scheduling", "tasks", "site_operations"],
    tags: ["backstage", "production"],
  }),
  defineLiveEventRole({
    key: "bartender",
    label: "Bartender",
    department: "Food & Beverage",
    role_category: "bar_service",
    employment_type: "part_time",
    job_summary: "Provides beverage service while following venue, event, and jurisdictional alcohol-service requirements.",
    duties: ["Prepare and serve approved beverages", "Verify service eligibility as required and follow responsible-service procedures", "Maintain assigned bar inventory, cleanliness, and POS workflow"],
    qualifications: ["Bartending or high-volume beverage-service experience", "Customer-service, POS, and responsible-service knowledge"],
    required_credentials: [
      credential("alcohol-server", "Alcohol server permit / certification where required", { jurisdictionDependent: true }),
      credential("food-handler", "Food-handler credential where required", { isRequired: false, jurisdictionDependent: true }),
    ],
    essentials: ["Valid role-required permits for the event jurisdiction", "POS access if assigned", "Shift, break, and incident-reporting procedures"],
    surfaces: ["inventory", "timekeeping", "scheduling", "incident_reporting"],
    tags: ["bar", "beverage"],
  }),
  defineLiveEventRole({
    key: "booking-agent",
    label: "Booking Agent",
    department: "Talent & Booking",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Represents talent or buyers in negotiating and coordinating performance bookings.",
    duties: ["Source and evaluate booking opportunities", "Negotiate commercial and scheduling terms within authorized limits", "Coordinate holds, confirmations, contracts, and advancing handoffs"],
    qualifications: ["Professional booking, agency, talent-buying, or artist-management experience", "Contract literacy, negotiation, and relationship-management skills"],
    required_credentials: [],
    essentials: ["Authorized deal parameters and contacts", "Contract and approval workflow access", "Accurate hold, offer, and confirmation tracking"],
    surfaces: ["crm", "contracts", "advancing", "finance"],
    shiftBased: false,
    tags: ["booking", "talent"],
  }),
  defineLiveEventRole({
    key: "box-office-staff",
    label: "Box Office Staff",
    department: "Ticketing",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Supports ticket sales, will-call, guest lookup, and ticket-resolution operations.",
    duties: ["Process ticket and will-call transactions", "Resolve supported ticket issues or escalate exceptions", "Maintain accurate box-office and access-control handoffs"],
    qualifications: ["Customer-service and ticketing/POS experience preferred", "Accuracy, communication, and basic troubleshooting skills"],
    required_credentials: [],
    essentials: ["Authorized ticketing-system access", "POS permissions appropriate to assignment", "Escalation path for fraud, refunds, and access exceptions"],
    surfaces: ["ticketing", "access_control", "finance", "incident_reporting"],
    tags: ["box-office", "ticketing"],
  }),
  defineLiveEventRole({
    key: "brand-activations-team",
    label: "Brand Activations Team",
    department: "Partnerships",
    role_category: "creative",
    employment_type: "part_time",
    job_summary: "Executes sponsor and brand experiences according to approved activation plans and contractual deliverables.",
    duties: ["Set up and operate assigned brand-activation elements", "Engage guests according to brand and event guidelines", "Document deliverables, inventory, and issues for sponsor reporting"],
    qualifications: ["Experiential-marketing, promotions, or guest-engagement experience preferred", "Reliable presentation, communication, and reporting skills"],
    required_credentials: [],
    essentials: ["Approved activation brief and brand guidelines", "Inventory/checklist access", "Proof-of-performance workflow where authorized"],
    surfaces: ["sponsor_deliverables", "inventory", "tasks", "scheduling"],
    tags: ["brand", "sponsorship", "activation"],
  }),
  defineLiveEventRole({
    key: "camping-operations",
    label: "Camping Operations",
    department: "Site Operations",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Supports guest camping areas, check-in, wayfinding, services, and operational issue routing.",
    duties: ["Support campground entry, placement, wayfinding, and guest services", "Coordinate sanitation, water, safety, and transportation issues", "Report site hazards and unresolved guest issues"],
    qualifications: ["Festival, campground, guest-services, or site-operations experience preferred", "Outdoor work readiness and strong guest communication"],
    required_credentials: [],
    essentials: ["Current campground map and operating plan", "Reliable communications access", "Knowledge of emergency and guest-escalation procedures"],
    surfaces: ["site_operations", "guest_services", "transportation", "incident_reporting"],
    tags: ["camping", "site-operations"],
  }),
  defineLiveEventRole({
    key: "catering-team",
    label: "Catering Team",
    department: "Food & Beverage",
    role_category: "hospitality",
    employment_type: "part_time",
    job_summary: "Prepares, distributes, and maintains approved meal and catering service for crew, artists, and guests.",
    duties: ["Execute assigned food-prep, service, and replenishment tasks", "Follow food-safety, allergen, and sanitation procedures", "Coordinate meal counts and timing with hospitality and production"],
    qualifications: ["Food-service or catering experience preferred", "Ability to follow food-safety and allergen procedures"],
    required_credentials: [credential("food-handler", "Food-handler card / certification where required", { jurisdictionDependent: true })],
    essentials: ["Allergen and dietary information access where needed", "Approved food-safety procedures and PPE", "Meal-count and service schedule"],
    surfaces: ["catering", "inventory", "compliance", "scheduling"],
    tags: ["catering", "food-service"],
  }),
  defineLiveEventRole({
    key: "cleaning-crew",
    label: "Cleaning Crew",
    department: "Site Operations",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Maintains assigned event areas for cleanliness, sanitation, and safe guest/crew use.",
    duties: ["Clean and restock assigned areas", "Identify spills, waste, or hazards and resolve or escalate them", "Record completed zones and supply needs"],
    qualifications: ["Commercial cleaning or event-operations experience preferred", "Ability to follow chemical, waste, and PPE procedures"],
    required_credentials: [credential("hazcom", "Hazard communication / chemical safety training where applicable", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Access to approved supplies and safety information", "PPE appropriate to assigned tasks", "Zone checklist and escalation contacts"],
    surfaces: ["site_operations", "inventory", "tasks", "incident_reporting"],
    tags: ["cleaning", "sanitation"],
  }),
  defineLiveEventRole({
    key: "content-creators",
    label: "Content Creators",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Creates approved social, editorial, or promotional media that documents and promotes the event.",
    duties: ["Capture or produce assigned content", "Follow event, artist, sponsor, and rights guidelines", "Deliver files, captions, and metadata through the approved media workflow"],
    qualifications: ["Portfolio demonstrating relevant content production", "Working knowledge of platform formats, releases, and brand guidelines"],
    required_credentials: [],
    essentials: ["Approved shot/content list and access permissions", "Rights/release and embargo guidance", "Defined file-delivery and review process"],
    surfaces: ["content_calendar", "media_library", "approvals", "sponsor_deliverables"],
    tags: ["content", "media", "creator"],
  }),
  defineLiveEventRole({
    key: "creative-director",
    label: "Creative Director",
    department: "Media & Marketing",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads the event's visual and creative direction across marketing, environments, and audience-facing assets.",
    duties: ["Set and maintain creative direction", "Review creative work for consistency and campaign objectives", "Coordinate designers, content teams, production, and sponsor requirements"],
    qualifications: ["Senior creative-leadership experience with a strong portfolio", "Ability to manage multidisciplinary creative production and approvals"],
    required_credentials: [],
    essentials: ["Approved brand system and campaign objectives", "Creative approval authority and deadlines", "Rights, sponsor, and production constraints"],
    surfaces: ["approvals", "content_calendar", "tasks", "sponsor_deliverables"],
    shiftBased: false,
    tags: ["creative", "design"],
  }),
  defineLiveEventRole({
    key: "crowd-control-staff",
    label: "Crowd Control Staff",
    department: "Security",
    role_category: "security",
    employment_type: "part_time",
    job_summary: "Supports safe guest flow, queueing, and access boundaries under the event security and operations plan.",
    duties: ["Monitor assigned crowd-flow areas", "Provide direction and escalate unsafe conditions", "Support queue, egress, and restricted-area boundaries as assigned"],
    qualifications: ["Event security, guest-services, or crowd-management experience preferred", "Clear communication and de-escalation capability"],
    required_credentials: [credential("security-license", "Security credential where role/jurisdiction requires it", { isRequired: false, jurisdictionDependent: true })],
    essentials: ["Post assignment and escalation instructions", "Radio access when required", "Understanding of emergency egress and accessibility routes"],
    surfaces: ["security", "site_operations", "credentials", "incident_reporting"],
    tags: ["crowd-control", "security"],
  }),
  defineLiveEventRole({
    key: "credentialing-staff",
    label: "Credentialing Staff",
    department: "Access & Credentials",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Issues, validates, and troubleshoots event credentials and approved access levels.",
    duties: ["Verify approved recipient identity/status", "Issue or replace credentials according to policy", "Escalate access disputes, fraud indicators, or database mismatches"],
    qualifications: ["Credentialing, registration, ticketing, or access-control experience preferred", "Accuracy, privacy awareness, and customer-service skills"],
    required_credentials: [],
    essentials: ["Authorized credentialing-system access", "Current access matrix and issuance rules", "Audit trail for issuance, replacement, and revocation"],
    surfaces: ["credentials", "access_control", "audit", "incident_reporting"],
    tags: ["credentials", "access-control"],
  }),
  defineLiveEventRole({
    key: "data-analytics-team",
    label: "Data + Analytics Team",
    department: "Data & Technology",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Collects, validates, and analyzes event data to support operational and business decisions.",
    duties: ["Maintain approved dashboards and data feeds", "Monitor data quality and document anomalies", "Produce scheduled and ad-hoc analysis for authorized teams"],
    qualifications: ["Analytics, BI, data-engineering, or event-operations analysis experience", "Strong SQL, spreadsheet, or dashboard skills appropriate to assignment"],
    required_credentials: [],
    essentials: ["Approved data access and privacy scope", "Defined source-of-truth metrics", "Issue and change-log workflow"],
    surfaces: ["analytics", "reporting", "data_governance", "tasks"],
    shiftBased: false,
    tags: ["analytics", "data"],
  }),
  defineLiveEventRole({
    key: "drone-operator",
    label: "Drone Operator",
    department: "Media & Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Operates unmanned aircraft only within approved legal, safety, airspace, and site parameters for authorized event work.",
    duties: ["Plan authorized flights with production and site leadership", "Operate aircraft within applicable aviation and site rules", "Maintain required flight records and stop operations when conditions are unsafe"],
    qualifications: ["Documented UAS operating experience appropriate to the mission", "Knowledge of local airspace, event restrictions, and safety procedures"],
    required_credentials: [credential("uas-pilot", "Applicable remote-pilot / UAS credential", { authority: "Aviation authority", jurisdictionDependent: true })],
    essentials: ["Written flight authorization and approved operating area", "Weather and airspace check workflow", "Spotter/communications plan when required"],
    surfaces: ["permits", "weather", "scheduling", "incident_reporting"],
    tags: ["drone", "uas", "aerial"],
  }),
  defineLiveEventRole({
    key: "emergency-response-team",
    label: "Emergency Response Team",
    department: "Safety & Emergency",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Coordinates assigned emergency-response functions under the approved emergency action and incident-command plan.",
    duties: ["Respond within the assigned emergency role", "Coordinate with medical, security, fire, and venue/site leadership", "Document incidents and resource requests according to the emergency plan"],
    qualifications: ["Relevant emergency-management, public-safety, or event-response experience", "Training appropriate to the assigned emergency function"],
    required_credentials: [
      credential("ics", "Incident Command System training appropriate to role", { isRequired: false, isExpiryTracked: false }),
      credential("first-aid", "First aid / CPR where assigned", { isRequired: false }),
    ],
    essentials: ["Current emergency action plan and chain of command", "Reliable emergency communications", "Clear scope of authority and agency handoff procedures"],
    surfaces: ["incident_command", "incident_reporting", "weather", "site_operations"],
    tags: ["emergency", "response", "safety"],
  }),
  defineLiveEventRole({
    key: "entertainment-lawyer",
    label: "Entertainment Lawyer",
    department: "Legal & Business Affairs",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Provides legal counsel on event, talent, rights, sponsorship, licensing, and related business matters.",
    duties: ["Review and advise on contracts and legal issues", "Support rights, licensing, claims, and risk questions", "Coordinate with leadership and outside counsel as authorized"],
    qualifications: ["Licensed attorney in the relevant jurisdiction and entertainment/business-law experience", "Strong contract, rights, and risk-analysis skills"],
    required_credentials: [credential("bar-license", "Active law license in applicable jurisdiction", { authority: "Applicable bar/licensing authority", jurisdictionDependent: true })],
    essentials: ["Attorney-client confidentiality controls", "Authorized document access", "Clear approval and escalation authority"],
    surfaces: ["contracts", "legal", "approvals", "risk"],
    shiftBased: false,
    tags: ["legal", "law"],
  }),
  defineLiveEventRole({
    key: "fence-barricade-crew",
    label: "Fence + Barricade Crew",
    department: "Site Operations",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Installs, inspects, and adjusts approved fencing and barricade systems under the site plan.",
    duties: ["Install assigned fence/barricade runs to approved layout", "Inspect for stability, access, and egress conflicts", "Report or correct approved configuration issues with site leadership"],
    qualifications: ["Event-site, staging, construction, or labor experience preferred", "Ability to follow plans, teamwork, and site-safety procedures"],
    required_credentials: [credential("site-safety", "Site / construction safety orientation", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Approved site plan and change authority", "Required PPE and tools", "Coordination with security, fire lanes, and accessibility routes"],
    surfaces: ["site_operations", "tasks", "inventory", "incident_reporting"],
    tags: ["fencing", "barricade", "site"],
  }),
  defineLiveEventRole({
    key: "festival-founder",
    label: "Festival Founder",
    department: "Executive",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Sets the festival's strategic vision, ownership priorities, and executive decision framework.",
    duties: ["Set strategic goals and major business priorities", "Approve executive budgets, partnerships, and high-level risk decisions", "Delegate operational authority and maintain governance oversight"],
    qualifications: ["Founder, executive, or ownership-level experience relevant to the event organization", "Leadership, financial, and stakeholder-management capability"],
    required_credentials: [],
    essentials: ["Defined decision rights and delegation matrix", "Access to executive reporting and risk registers", "Documented approvals for major commitments"],
    surfaces: ["executive_dashboard", "finance", "approvals", "risk"],
    shiftBased: false,
    tags: ["executive", "founder"],
  }),
  defineLiveEventRole({
    key: "finance-payroll-team",
    label: "Finance + Payroll Team",
    department: "Finance",
    role_category: "operations",
    employment_type: "contractor",
    job_summary: "Manages approved financial processing, payroll coordination, reconciliations, and workforce payment records.",
    duties: ["Process approved payroll/payment inputs", "Reconcile labor, vendor, and event financial records", "Maintain audit-ready records and escalate exceptions"],
    qualifications: ["Finance, payroll, accounting, or event-business operations experience", "High accuracy and confidentiality with financial data"],
    required_credentials: [credential("payroll-compliance", "Payroll/compliance training appropriate to jurisdiction and employer", { isRequired: false, isExpiryTracked: false, jurisdictionDependent: true })],
    essentials: ["Role-based access to sensitive financial data", "Approval thresholds and audit trail", "Published payroll cutoff and exception workflow"],
    surfaces: ["payroll", "finance", "timekeeping", "approvals", "audit"],
    shiftBased: false,
    tags: ["finance", "payroll"],
  }),
  defineLiveEventRole({
    key: "food-vendor",
    label: "Food Vendor",
    department: "Vendors",
    role_category: "hospitality",
    employment_type: "contractor",
    job_summary: "Operates an approved food concession or service under event, health, and vendor requirements.",
    duties: ["Operate within assigned vendor footprint and hours", "Follow food-safety, sanitation, waste, and payment requirements", "Coordinate deliveries, inspections, and issues with vendor operations"],
    qualifications: ["Relevant food-service operating experience", "Ability to meet event vendor and local health requirements"],
    required_credentials: [
      credential("health-permit", "Food-service / health permit(s) required by jurisdiction", { jurisdictionDependent: true }),
      credential("food-handler", "Food-handler certification where required", { jurisdictionDependent: true }),
    ],
    essentials: ["Approved vendor agreement and footprint", "Power/water/waste requirements documented", "Inspection and emergency-contact workflow"],
    surfaces: ["vendors", "permits", "site_operations", "finance"],
    tags: ["food", "vendor"],
  }),
  defineLiveEventRole({
    key: "generator-power-crew",
    label: "Generator + Power Crew",
    department: "Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Supports temporary event power distribution, generators, and related electrical infrastructure within authorized scope.",
    duties: ["Monitor assigned power systems and status checks", "Coordinate approved power changes with production and site teams", "Report faults, overload indicators, or unsafe conditions immediately"],
    qualifications: ["Live-event temporary-power or electrical experience appropriate to assignment", "Knowledge of electrical safety and power-distribution practices"],
    required_credentials: [credential("electrical-qualification", "Electrical license / qualification where required for assigned work", { jurisdictionDependent: true })],
    essentials: ["Power plan access where applicable", "Authorized emergency-shutdown procedures", "Required PPE and restricted-system access"],
    surfaces: ["equipment", "site_operations", "scheduling", "incident_reporting"],
    tags: ["power", "generator", "electrical"],
  }),
  defineLiveEventRole({
    key: "golf-cart-driver",
    label: "Golf Cart Driver",
    department: "Transportation",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Provides authorized low-speed transport for staff, artists, guests, or materials within the event site.",
    duties: ["Operate assigned cart on approved routes", "Perform pre-use checks and report damage", "Follow pedestrian, capacity, parking, and charging/fueling rules"],
    qualifications: ["Safe driving history and event-site awareness", "Experience operating utility carts preferred"],
    required_credentials: [credential("driver-license", "Valid driver license where required by policy or jurisdiction", { isRequired: false, jurisdictionDependent: true })],
    essentials: ["Authorized route map and parking rules", "Vehicle assignment/checklist", "Dispatch access when assigned"],
    surfaces: ["transportation", "dispatch", "equipment", "incident_reporting"],
    tags: ["driver", "golf-cart"],
  }),
  defineLiveEventRole({
    key: "graphic-designer",
    label: "Graphic Designer",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Creates visual assets for event marketing, signage, digital products, and sponsor deliverables.",
    duties: ["Design assigned creative assets", "Prepare production-ready files to specification", "Revise work through the approved review process"],
    qualifications: ["Professional design portfolio and proficiency with required design tools", "Strong typography, layout, and brand-system skills"],
    required_credentials: [],
    essentials: ["Current brand guidelines and asset library", "Approved specs, deadlines, and review owners", "Rights-cleared source assets"],
    surfaces: ["media_library", "content_calendar", "approvals", "sponsor_deliverables"],
    shiftBased: false,
    tags: ["graphic-design", "creative"],
  }),
  defineLiveEventRole({
    key: "grounds-crew",
    label: "Grounds Crew",
    department: "Site Operations",
    role_category: "operations",
    employment_type: "part_time",
    job_summary: "Maintains outdoor event grounds, pathways, and assigned site infrastructure throughout operations.",
    duties: ["Inspect and maintain assigned ground areas", "Address or report trip, drainage, surface, and site-condition issues", "Support approved site resets and weather-response tasks"],
    qualifications: ["Grounds, facilities, landscaping, or event-site experience preferred", "Ability to follow site-safety and weather procedures"],
    required_credentials: [],
    essentials: ["Zone assignment and site map", "Required PPE/tools", "Hazard-reporting and weather-escalation path"],
    surfaces: ["site_operations", "weather", "tasks", "incident_reporting"],
    tags: ["grounds", "site"],
  }),
  defineLiveEventRole({
    key: "hair-makeup",
    label: "Hair + Makeup",
    department: "Artist Services",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Provides approved hair and makeup services for performers, presenters, or production needs.",
    duties: ["Prepare and deliver assigned looks", "Maintain hygiene and kit sanitation", "Coordinate timing and changes with artist/stage teams"],
    qualifications: ["Professional hair/makeup portfolio and production experience appropriate to assignment", "Strong sanitation, time-management, and talent-facing skills"],
    required_credentials: [credential("cosmetology-license", "Cosmetology or specialty license where legally required", { isRequired: false, jurisdictionDependent: true })],
    essentials: ["Approved look references and schedule", "Sanitized professional kit", "Private and respectful artist-service environment"],
    surfaces: ["artist_services", "scheduling", "tasks", "media_library"],
    tags: ["hair", "makeup", "artist-services"],
  }),
  defineLiveEventRole({
    key: "hospitality-manager",
    label: "Hospitality Manager",
    department: "Hospitality",
    role_category: "management",
    employment_type: "contractor",
    job_summary: "Leads hospitality operations for artists, crew, guests, and designated service areas.",
    duties: ["Plan and supervise hospitality staffing and service", "Coordinate catering, dressing rooms, VIP, and supply needs", "Resolve service issues and track cross-department handoffs"],
    qualifications: ["Hospitality, venue, festival, or event-management experience", "Team leadership, vendor coordination, and service-recovery skills"],
    required_credentials: [],
    essentials: ["Hospitality plan, budget, and service standards", "Staffing and vendor contact access", "Issue-escalation authority"],
    surfaces: ["catering", "vendors", "scheduling", "tasks"],
    tags: ["hospitality", "management"],
  }),
  defineLiveEventRole({
    key: "influencer-creator-relations",
    label: "Influencer + Creator Relations",
    department: "Media & Marketing",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Coordinates invited creators and influencer partnerships from outreach through access and deliverables.",
    duties: ["Manage creator invitations, credentials, and schedules", "Communicate content guidelines, deliverables, and disclosure requirements", "Track posts, assets, and contractual obligations"],
    qualifications: ["Influencer/creator marketing, PR, or partnerships experience", "Strong relationship management and campaign tracking"],
    required_credentials: [],
    essentials: ["Approved creator roster and terms", "Disclosure and brand-safety guidelines", "Credential, content, and deliverable tracking"],
    surfaces: ["crm", "credentials", "content_calendar", "sponsor_deliverables"],
    shiftBased: false,
    tags: ["influencer", "creator-relations"],
  }),
  defineLiveEventRole({
    key: "internet-wifi-team",
    label: "Internet + WiFi Team",
    department: "Data & Technology",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Deploys and supports event connectivity for approved production, operations, vendor, and guest use cases.",
    duties: ["Monitor assigned network infrastructure and service health", "Troubleshoot approved connectivity incidents", "Coordinate changes, access, and escalations with production and IT leads"],
    qualifications: ["Network engineering/support experience appropriate to event scale", "Knowledge of wired/wireless networking, monitoring, and secure access practices"],
    required_credentials: [credential("network-safety", "Site/network safety orientation", { isRequired: false, isExpiryTracked: false })],
    essentials: ["Network map and approved admin access", "Change-management and incident-ticketing path", "Backup-connectivity escalation contacts"],
    surfaces: ["network_ops", "equipment", "tasks", "incident_reporting"],
    tags: ["network", "wifi", "internet"],
  }),
  defineLiveEventRole({
    key: "id-check-staff",
    label: "ID Check Staff",
    department: "Access & Credentials",
    role_category: "security",
    employment_type: "part_time",
    job_summary: "Verifies age or identity at designated checkpoints according to event and legal requirements.",
    duties: ["Inspect accepted identity documents according to policy", "Direct guests to the resolution path for exceptions", "Report suspected fraud or safety concerns"],
    qualifications: ["Customer-service, access-control, or regulated-service experience preferred", "Ability to follow document-check and privacy procedures consistently"],
    required_credentials: [credential("id-verification-training", "ID verification / responsible-service training where required", { isRequired: false, isExpiryTracked: false, jurisdictionDependent: true })],
    essentials: ["Current accepted-ID policy", "Escalation procedure for disputed or suspicious documents", "No retention of identity data outside approved workflow"],
    surfaces: ["access_control", "compliance", "scheduling", "incident_reporting"],
    tags: ["id-check", "access-control"],
  }),
  defineLiveEventRole({
    key: "led-visual-operator",
    label: "LED Visual Operator",
    department: "Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Operates approved LED/video playback systems and show visuals in coordination with production cues.",
    duties: ["Load and operate approved visual content", "Execute cues and monitor display-system status", "Coordinate technical issues with video, lighting, and production teams"],
    qualifications: ["Live-event video/LED playback experience", "Proficiency with assigned playback/control systems"],
    required_credentials: [],
    essentials: ["Approved show content and cue list", "System access and backup media", "Reliable communications with stage/production"],
    surfaces: ["run_of_show", "media_library", "equipment", "incident_reporting"],
    tags: ["led", "video", "visuals"],
  }),
  defineLiveEventRole({
    key: "lighting-designer",
    label: "Lighting Designer",
    department: "Production",
    role_category: "creative",
    employment_type: "contractor",
    job_summary: "Designs and directs the artistic lighting approach for performances and event environments.",
    duties: ["Develop lighting design within venue, artist, and production constraints", "Create or supervise programming and cue structure", "Coordinate with production, video, audio, and stage teams"],
    qualifications: ["Professional live-event lighting-design experience and portfolio", "Knowledge of fixtures, control systems, power, and production workflow"],
    required_credentials: [],
    essentials: ["Approved plot/specification and show schedule", "Programming and system access", "Change and cue-approval path"],
    surfaces: ["advancing", "run_of_show", "equipment", "approvals"],
    tags: ["lighting", "design"],
  }),
  defineLiveEventRole({
    key: "livestream-team",
    label: "Livestream Team",
    department: "Media & Production",
    role_category: "technical",
    employment_type: "contractor",
    job_summary: "Produces and operates approved live-video streams and remote-broadcast workflows.",
    duties: ["Prepare streaming, switching, encoding, and monitoring systems", "Execute broadcast cues and monitor stream health", "Coordinate rights, signal, graphics, and contingency issues"],
    qualifications: ["Live broadcast/streaming-production experience appropriate to role", "Knowledge of encoding, switching, networking, and media delivery"],
    required_credentials: [],
    essentials: ["Streaming credentials and destination access", "Rights and embargo authorization", "Backup path and incident escalation"],
    surfaces: ["run_of_show", "media_library", "network_ops", "incident_reporting"],
    tags: ["livestream", "broadcast"],
  }),
  defineLiveEventRole({
    key: "logistics-coordinator",
    label: "Logistics Coordinator",
    department: "Logistics",
    role_category: "operations",
    employment_type: "contractor",
    job_summary: "Coordinates movement of people, equipment, and deliveries across event timelines and locations.",
    duties: ["Track deliveries, pickups, and movement requests", "Coordinate loading zones, schedules, and internal handoffs", "Maintain status updates and escalate conflicts"],
    qualifications: ["Event, touring, warehouse, freight, or logistics experience", "Strong scheduling, tracking, and communication skills"],
    required_credentials: [],
    essentials: ["Master logistics schedule and contact list", "Loading/access rules and route maps", "Change log and escalation path"],
    surfaces: ["logistics", "transportation", "inventory", "scheduling"],
    tags: ["logistics", "coordination"],
  }),
]
