/**
 * REP-101 — Inventory of admin reporting consumers (dashboard/card/chart/export/query).
 * Each consumer documents source, formula, org filter, failure, owner, replacement, retirement.
 */

export type ReportingConsumerKind =
  | 'dashboard'
  | 'card'
  | 'chart'
  | 'export'
  | 'query'
  | 'widget'

export type ReportingOrgFilter = 'yes' | 'partial' | 'no' | 'n/a'

export type ReportingFailureBehavior =
  | 'empty'
  | 'error'
  | 'mock'
  | 'degraded'
  | 'unknown'

export type ReportingRetirementPlan =
  | 'keep'
  | 'replace'
  | 'retire'
  | 'consolidate'

export interface ReportingConsumer {
  id: string
  kind: ReportingConsumerKind
  surface: string
  source: string
  formula: string
  orgFilter: ReportingOrgFilter
  failureBehavior: ReportingFailureBehavior
  owner: string
  canonicalReplacement: string
  retirementPlan: ReportingRetirementPlan
  /** Zero-mock policy violation or other risk */
  notes?: string
}

export const REPORTING_CONSUMERS: ReportingConsumer[] = [
  // --- Dashboards ---
  {
    id: 'REP-DASH-ANALYTICS',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/analytics/page.tsx',
    source: '/api/admin/dashboard/stats, finances overview, events, top-performers',
    formula: 'Fan-out UI; client re-aggregates txs/events for charts',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Governed org KPI read model (REP-201+)',
    retirementPlan: 'consolidate',
    notes: 'EMPTY_STATS zeros on fail; date range ignored by stats API',
  },
  {
    id: 'REP-DASH-HOME-OPTIMIZED',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/components/optimized-dashboard-client.tsx',
    source: '/api/admin/dashboard/stats (+ tours/events lists)',
    formula: 'Pass-through stats into AdminStatCards',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'admin-misc',
    canonicalReplacement: 'Same KPI catalog as analytics',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-DASH-ANALYTICS-EMBED',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/components/analytics-dashboard.tsx',
    source: 'useDashboardStats / tours / events / artists / venues hooks',
    formula: 'Client utilization, successRate, revenueGrowth; synthetic daily revenue fill',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Domain aggregate APIs',
    retirementPlan: 'replace',
    notes: 'Fabricates monthlyRevenue/30 when no day events',
  },
  {
    id: 'REP-DASH-FINANCES',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/finances/page.tsx',
    source: '/api/admin/finances?type=overview, /settlements',
    formula: 'RPC totals; client monthly chart from recent txs',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-finance',
    canonicalReplacement: 'FIN profitability read model (REP-502)',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-DASH-TICKETING',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/ticketing/page.tsx',
    source: '/api/admin/ticketing/enhanced?type=overview',
    formula: 'RPC overview + client mapping; trends forced 0',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'Canonical ticketing read model (REP-501)',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-DASH-LOGISTICS',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/logistics/logistics-page-client.tsx',
    source: '/api/admin/logistics/metrics',
    formula: 'Domain % = completed/total per task type + travel/lodging/rentals',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-logistics',
    canonicalReplacement: 'REP-301 logistics dashboard contract',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-DASH-CONTENT-HUB',
    kind: 'dashboard',
    surface: 'components/admin/content-hub/content-hub-shell.tsx',
    source: '/api/admin/content-hub/overview, /analytics',
    formula: 'Meta followers/impressions/reach sums; org post engagement',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'content',
    canonicalReplacement: 'Content-hub analytics contract; align org key',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-DASH-CMD-CENTER',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/events/[id]/command-center/page.tsx',
    source: '/api/events/{id}/hq',
    formula: 'Count/length aggregates + last-activity max',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'ops-events',
    canonicalReplacement: 'tour_command_center_summary contract (REP-201) + event ops projection',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-QUERY-TOUR-CMD-SUMMARY',
    kind: 'query',
    surface: 'GET /api/admin/tours/[id]/summary',
    source: 'lib/admin/tour-command-center-summary.ts + command-center-summary-contract.ts',
    formula: 'Governed domainMetrics (null when denied/unavailable); risks with remediationUrl',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-tours',
    canonicalReplacement: 'tour_command_center_summary (REP-201 contract v1) + REP-202 projection',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-TOUR-CMD-PROJECTION',
    kind: 'query',
    surface: 'GET|POST /api/admin/tours/[id]/summary/projection',
    source: 'tour_command_center_summary_projections + watermarks + outbox apply',
    formula: 'Idempotent outbox apply; per-source lag; live vs projected reconcile',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-tours',
    canonicalReplacement: 'tour_command_center_summary projection (REP-202)',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-DASH-MARKETPLACE-ORDERS',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/marketplace/orders/page.tsx',
    source: 'marketplace orders API',
    formula: 'Revenue = sum paid/completed; pending count',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'commerce-marketplace',
    canonicalReplacement: 'Commercial order ledger aggregates',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-DASH-LEGACY-MOCK',
    kind: 'dashboard',
    surface: 'app/admin/dashboard/components/dashboard.tsx',
    source: 'Hardcoded mock state',
    formula: 'Mock constants (e.g. revenue 2.48M)',
    orgFilter: 'n/a',
    failureBehavior: 'mock',
    owner: 'admin-misc',
    canonicalReplacement: 'None — delete',
    retirementPlan: 'retire',
    notes: 'ZERO-MOCK violation',
  },

  // --- Cards / widgets ---
  {
    id: 'REP-CARD-ANALYTICS-KPI',
    kind: 'card',
    surface: 'analytics page AdminStatCards',
    source: 'dashboard stats',
    formula: 'totalRevenue, totalEvents, ticketsSold, upcomingEvents pass-through',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'KPI catalog IDs',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-CARD-ANALYTICS-PERF',
    kind: 'card',
    surface: 'analytics PerformanceMetric',
    source: 'stats rates',
    formula: 'coordination/logistics %; activeTours/totalTours',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Operational KPI set (REP-301/401)',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-CARD-HOME-KPI',
    kind: 'card',
    surface: 'optimized-dashboard AdminStatCards',
    source: 'dashboard stats',
    formula: 'tours/events/revenue/tickets',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'admin-misc',
    canonicalReplacement: 'Same KPI catalog',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-CARD-FIN-OVERVIEW',
    kind: 'card',
    surface: 'finances page overview cards',
    source: 'get_finance_overview RPC',
    formula: 'income, expenses, net, allocated, spent, remaining, pending, overdue',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-finance',
    canonicalReplacement: 'REP-502',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-CARD-TIX-OVERVIEW',
    kind: 'card',
    surface: 'ticketing page KPI row',
    source: 'get_admin_ticketing_overview',
    formula: 'sold, revenue, avg price; conversion=socialConversions/clicks; trends hardcoded 0',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'REP-501',
    retirementPlan: 'replace',
    notes: 'weekly_trend/revenue_trend hardcoded 0',
  },
  {
    id: 'REP-CARD-CONTENT-OVERVIEW',
    kind: 'card',
    surface: 'components/admin/content-hub/content-overview-panel.tsx',
    source: 'content-hub overview',
    formula: 'connectedCount, meta totals, orgPosts engagement',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'content',
    canonicalReplacement: 'keep',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-CARD-STAFF-ANALYTICS',
    kind: 'card',
    surface: 'components/admin/staff-analytics-panel.tsx',
    source: '/api/admin/staff, job-postings, applications, shifts',
    formula: 'Client counts + MTD shift hours',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'workforce',
    canonicalReplacement: 'REP-401 workforce dashboard',
    retirementPlan: 'consolidate',
    notes: 'Possibly unused import',
  },
  {
    id: 'REP-CARD-SCHED-OVERVIEW',
    kind: 'card',
    surface: 'components/admin/scheduling/scheduling-overview-cards.tsx',
    source: 'scheduling context shifts/conflicts',
    formula: 'counts: shifts, confirmed, open, critical conflicts, pending',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'workforce',
    canonicalReplacement: 'REP-401',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-WIDGET-LOGISTICS-PROGRESS',
    kind: 'widget',
    surface: 'components/admin/operations/logistics-progress-widget.tsx',
    source: 'parent-supplied summary',
    formula: 'display % / completed/items',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'ops-logistics',
    canonicalReplacement: 'REP-301',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-WIDGET-BATCH-LOGISTICS',
    kind: 'widget',
    surface: 'lib/admin/batch-logistics-metrics.ts',
    source: 'fan-out metrics + tour logistics-summary',
    formula: 'sum categories → completion %',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'ops-logistics',
    canonicalReplacement: 'Batch aggregate endpoint',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-CARD-TIX-READMODEL',
    kind: 'widget',
    surface: 'components/admin/ticketing/ticketing-read-model-panel.tsx',
    source: '/api/admin/ticketing/read-model',
    formula: 'Dual-read legacy vs canonical; cutover blockers',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'Canonical only post-cutover',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-CARD-NETWORK',
    kind: 'card',
    surface: 'app/admin/dashboard/network/page.tsx',
    source: 'network APIs',
    formula: 'request/connection counts',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Out of core REP commercial/ops',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-CARD-MARKETPLACE-PAYOUTS',
    kind: 'query',
    surface: 'marketplace MarketplacePayoutsList',
    source: 'finances overview recentTransactions',
    formula: 'Pass-through filter (looks for wrong field transactions)',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'commerce-marketplace',
    canonicalReplacement: 'Finance payout ledger query',
    retirementPlan: 'replace',
    notes: 'Reads d.transactions but overview returns recentTransactions',
  },

  // --- Charts ---
  {
    id: 'REP-CHART-ANALYTICS-REVENUE',
    kind: 'chart',
    surface: 'analytics page Area/Bar',
    source: 'finances recentTransactions (limit 10)',
    formula: 'Group by YYYY-MM; sum income vs expense',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Finance time-series aggregate',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-CHART-ANALYTICS-AUDIENCE',
    kind: 'chart',
    surface: 'analytics audience util',
    source: '/api/admin/events',
    formula: 'sold/capacity utilization top 10',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Ticketing capacity read model',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-CHART-ANALYTICS-PLACEHOLDER',
    kind: 'chart',
    surface: 'analytics ChartPlaceholderCard',
    source: 'none',
    formula: 'No data placeholder',
    orgFilter: 'n/a',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Real series or remove',
    retirementPlan: 'retire',
  },
  {
    id: 'REP-CHART-FIN-MONTHLY',
    kind: 'chart',
    surface: 'finances page BarChart',
    source: 'recent txs (overview limit 10)',
    formula: 'Monthly income/expense group',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'commerce-finance',
    canonicalReplacement: 'Full tx time-series API',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-CHART-TIX-SALES',
    kind: 'chart',
    surface: 'ticketing page AreaChart',
    source: 'enhanced sales',
    formula: 'Pass-through / client series',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'REP-501',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-CHART-EVENT-ANALYTICS',
    kind: 'chart',
    surface: 'events/[id] analytics tab',
    source: '/api/admin/events/[id]/analytics',
    formula: 'Sales by date/tier; conversion=sold/capacity; attendanceForecast=sold',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'ops-events',
    canonicalReplacement: 'Event commercial summary',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-CHART-STAFF-BY-ROLE',
    kind: 'chart',
    surface: 'staff-analytics-panel',
    source: 'staff list',
    formula: 'count by role',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'workforce',
    canonicalReplacement: 'REP-401',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-CHART-EMBED-HISTORY',
    kind: 'chart',
    surface: 'analytics-dashboard revenue history',
    source: 'events + monthlyRevenue',
    formula: 'Synthetic dailyRevenue fill when no day match',
    orgFilter: 'partial',
    failureBehavior: 'mock',
    owner: 'admin-misc',
    canonicalReplacement: 'Real daily ledger',
    retirementPlan: 'retire',
    notes: 'ZERO-MOCK synthetic series',
  },

  // --- Exports ---
  {
    id: 'REP-EXPORT-ANALYTICS-CSV',
    kind: 'export',
    surface: '/api/admin/analytics/export',
    source: 'financial_transactions, events_v2',
    formula: 'Pass-through rows → CSV sections',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'EXP-601 job + EXP-602 schema',
    retirementPlan: 'replace',
    notes: 'First org_members row; unscoped if no membership',
  },
  {
    id: 'REP-EXPORT-FINANCE-CLIENT-CSV',
    kind: 'export',
    surface: 'finances handleExportCSV',
    source: 'in-memory recent txs',
    formula: 'Pass-through rows (no formula injection guard)',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'commerce-finance',
    canonicalReplacement: 'Server export job + full dataset',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-EXPORT-CONTENT-HUB-CSV',
    kind: 'export',
    surface: 'content-analytics-panel client download',
    source: 'analytics csvRows',
    formula: 'Pass-through platform+media rows',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'content',
    canonicalReplacement: 'EXP-601 optional',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-EXPORT-TOUR-PDF-CSV',
    kind: 'export',
    surface: '/api/admin/tours/[id]/export',
    source: 'tour, tour_events, team, vendors, financial_transactions',
    formula: 'PDF via tour-export-document; CSV sections; income/expense sums',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-tours',
    canonicalReplacement: 'EXP-603 tour book + EXP-601',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-EXPORT-EVENT-CSV-ICS-PDF',
    kind: 'export',
    surface: '/api/admin/events/[id]/export',
    source: 'ticket_sales, events_v2 settings',
    formula: 'Attendee CSV / ICS / PDF variants',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'ops-events',
    canonicalReplacement: 'EXP-601/604',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-EXPORT-ADVANCING-HTML',
    kind: 'export',
    surface: '/api/admin/events/[id]/advancing/export',
    source: 'advancing_documents + event',
    formula: 'HTML print doc pass-through fields',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'ops-events',
    canonicalReplacement: 'Tour-book section / EXP-603',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-EXPORT-CALENDAR-ICS',
    kind: 'export',
    surface: '/api/admin/calendar/export',
    source: 'aggregateAdminCalendarItems + projection',
    formula: 'ICS from projected calendar items',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-calendar',
    canonicalReplacement: 'EXP-604',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-EXPORT-SITEMAP-JSON',
    kind: 'export',
    surface: '/api/admin/logistics/site-maps/[id]/export',
    source: 'get_site_map_with_data RPC',
    formula: 'Pass-through JSON package + activity log',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'ops-logistics',
    canonicalReplacement: 'Keep domain export',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-EXPORT-INVENTORY-CLIENT-CSV',
    kind: 'export',
    surface: 'inventory page client',
    source: 'logistics items in UI',
    formula: 'Pass-through filtered rows',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'ops-logistics',
    canonicalReplacement: 'EXP-601 inventory schema',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-EXPORT-VENDOR-REPORT-STUB',
    kind: 'export',
    surface: '/api/admin/logistics/vendor/dashboard POST export_report',
    source: 'none',
    formula: 'Returns { reportData: {} }',
    orgFilter: 'no',
    failureBehavior: 'mock',
    owner: 'ops-logistics',
    canonicalReplacement: 'Vendor dashboard export (REP-503)',
    retirementPlan: 'replace',
    notes: 'ZERO-MOCK stub',
  },

  // --- Queries / APIs ---
  {
    id: 'REP-QUERY-DASHBOARD-STATS',
    kind: 'query',
    surface: '/api/admin/dashboard/stats',
    source: 'tours, events_v2, staff, logistics, ticket_sales, bookings, financial_transactions, …',
    formula: 'Ad-hoc counts; ticketsSold += approvedVenueBookings; averageRating always 0',
    orgFilter: 'partial',
    failureBehavior: 'degraded',
    owner: 'admin-misc',
    canonicalReplacement: 'Governed KPI projection',
    retirementPlan: 'replace',
    notes: 'Catch returns success:true + emptyStats (zero means failed); global artist/venue counts',
  },
  {
    id: 'REP-QUERY-TOP-PERFORMERS',
    kind: 'query',
    surface: '/api/admin/analytics/top-performers',
    source: 'event_participants, profiles; events by capacity',
    formula: 'Artist = participant frequency; tickets=capacity; revenue always 0',
    orgFilter: 'no',
    failureBehavior: 'empty',
    owner: 'admin-misc',
    canonicalReplacement: 'Org-scoped commercial ranking',
    retirementPlan: 'replace',
    notes: 'No org filter; ZERO-MOCK revenue',
  },
  {
    id: 'REP-QUERY-FINANCE-OVERVIEW',
    kind: 'query',
    surface: '/api/admin/finances type=overview',
    source: 'get_finance_overview RPC + recent txs + budgets',
    formula: 'SQL RPC totals; net/remaining derived in route',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-finance',
    canonicalReplacement: 'Keep as FIN read path',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-FINANCE-TX-BUDGET',
    kind: 'query',
    surface: 'finances type=transactions/budgets',
    source: 'financial_transactions, budgets',
    formula: 'Pass-through rows + field projection',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-finance',
    canonicalReplacement: 'keep',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-FINANCE-SETTLEMENTS',
    kind: 'query',
    surface: '/api/admin/finances/settlements',
    source: 'settlements via command/compat',
    formula: 'Pass-through list',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'commerce-finance',
    canonicalReplacement: 'REP-502 settlements',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-LOGISTICS-METRICS',
    kind: 'query',
    surface: '/api/admin/logistics/metrics',
    source: 'logistics_tasks, travel_groups, lodging_bookings, rental_agreements',
    formula: 'Per-domain completed/total %; accommodations active ratio',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'ops-logistics',
    canonicalReplacement: 'REP-301',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-TOUR-LOGISTICS-SUMMARY',
    kind: 'query',
    surface: '/api/admin/tours/[id]/logistics-summary',
    source: 'logistics_tasks by tour',
    formula: 'Bucket travel/lodging/equipment completion',
    orgFilter: 'yes',
    failureBehavior: 'empty',
    owner: 'ops-logistics',
    canonicalReplacement: 'REP-301',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-QUERY-EVENT-ANALYTICS',
    kind: 'query',
    surface: '/api/admin/events/[id]/analytics',
    source: 'ticket_sales, financial_transactions, events_v2, ticket_types',
    formula: 'Sales by date/tier; conversion=sold/capacity',
    orgFilter: 'partial',
    failureBehavior: 'empty',
    owner: 'ops-events',
    canonicalReplacement: 'Event commercial summary',
    retirementPlan: 'replace',
  },
  {
    id: 'REP-QUERY-TIX-ENHANCED',
    kind: 'query',
    surface: '/api/admin/ticketing/enhanced',
    source: 'RPC + tables',
    formula: 'Overview metrics with hardcoded trends',
    orgFilter: 'yes',
    failureBehavior: 'error',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'ticketing-read-model',
    retirementPlan: 'consolidate',
  },
  {
    id: 'REP-QUERY-TIX-READMODEL',
    kind: 'query',
    surface: '/api/admin/ticketing/read-model',
    source: 'dual-read loader',
    formula: 'Compare legacy vs canonical',
    orgFilter: 'yes',
    failureBehavior: 'degraded',
    owner: 'commerce-ticketing',
    canonicalReplacement: 'Canonical cutover',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-CONTENT-ANALYTICS',
    kind: 'query',
    surface: '/api/admin/content-hub/analytics',
    source: 'organization_social_integrations + media_insights + org posts',
    formula: 'buildOrgPlatformAnalyticsMap; csvRows server-side',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'content',
    canonicalReplacement: 'keep',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-CONTENT-OVERVIEW',
    kind: 'query',
    surface: '/api/admin/content-hub/overview',
    source: 'integrations + posts',
    formula: 'Attention list + meta sums',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'content',
    canonicalReplacement: 'keep',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-ONBOARDING-ANALYTICS',
    kind: 'query',
    surface: '/api/admin/onboarding/workflows/analytics',
    source: 'AdminOnboardingStaffService workflows',
    formula: 'counts + avg duration days; rejects mock-/fallback- ids with 503',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'workforce',
    canonicalReplacement: 'Venue/workforce analytics',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-POLLS-ANALYTICS',
    kind: 'query',
    surface: 'PollAnalyticsPanel → /api/polls/analytics',
    source: 'poll analytics lib',
    formula: 'Aggregate poll summaries',
    orgFilter: 'partial',
    failureBehavior: 'error',
    owner: 'shared-polls',
    canonicalReplacement: 'KPI catalog documentation',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-QUERY-STAFFING-PERFORMANCE',
    kind: 'query',
    surface: '/api/admin/staffing/performance',
    source: 'staffing performance route',
    formula: 'Performance records operational aggregates',
    orgFilter: 'partial',
    failureBehavior: 'unknown',
    owner: 'workforce',
    canonicalReplacement: 'REP-401',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-LIB-PLATFORM-ANALYTICS',
    kind: 'query',
    surface: 'lib/admin/content-hub/build-platform-analytics.ts',
    source: 'integration.analytics JSON',
    formula: 'Status-aware slices; unsupported ≠ synced zeros',
    orgFilter: 'n/a',
    failureBehavior: 'degraded',
    owner: 'content',
    canonicalReplacement: 'keep',
    retirementPlan: 'keep',
  },
  {
    id: 'REP-LIB-TOUR-EXPORT-DOC',
    kind: 'query',
    surface: 'lib/admin/tour-export-document.tsx',
    source: 'TourReportData',
    formula: 'PDF layout only',
    orgFilter: 'n/a',
    failureBehavior: 'empty',
    owner: 'ops-tours',
    canonicalReplacement: 'EXP-603',
    retirementPlan: 'keep',
  },
]

export const REPORTING_REQUIRED_KINDS: ReportingConsumerKind[] = [
  'dashboard',
  'card',
  'chart',
  'export',
  'query',
  'widget',
]

export function listZeroMockViolations(
  consumers: ReportingConsumer[] = REPORTING_CONSUMERS,
): ReportingConsumer[] {
  return consumers.filter(
    (c) =>
      c.failureBehavior === 'mock'
      || (c.notes || '').toUpperCase().includes('ZERO-MOCK'),
  )
}

export function assertRep101InventoryCoverage(
  consumers: ReportingConsumer[] = REPORTING_CONSUMERS,
): { ok: boolean; failures: string[] } {
  const failures: string[] = []
  const ids = new Set<string>()

  for (const c of consumers) {
    if (!c.id) failures.push('consumer missing id')
    if (ids.has(c.id)) failures.push(`duplicate id ${c.id}`)
    ids.add(c.id)
    if (!c.surface?.trim()) failures.push(`${c.id} missing surface`)
    if (!c.source?.trim()) failures.push(`${c.id} missing source`)
    if (!c.formula?.trim()) failures.push(`${c.id} missing formula`)
    if (!c.orgFilter) failures.push(`${c.id} missing orgFilter`)
    if (!c.failureBehavior) failures.push(`${c.id} missing failureBehavior`)
    if (!c.owner?.trim()) failures.push(`${c.id} missing owner`)
    if (!c.canonicalReplacement?.trim()) failures.push(`${c.id} missing canonicalReplacement`)
    if (!c.retirementPlan) failures.push(`${c.id} missing retirementPlan`)
  }

  for (const kind of REPORTING_REQUIRED_KINDS) {
    if (!consumers.some((c) => c.kind === kind))
      failures.push(`no consumer of kind ${kind}`)
  }

  if (listZeroMockViolations(consumers).length === 0)
    failures.push('expected at least one documented zero-mock violation for retirement tracking')

  if (!consumers.some((c) => c.orgFilter === 'no'))
    failures.push('expected at least one unscoped consumer documented (e.g. top-performers)')

  return { ok: failures.length === 0, failures }
}
