export const ADMIN_CARD = "rounded-sm bg-slate-900/60 border-slate-700/50 backdrop-blur-sm"
export const ADMIN_CARD_HOVER = "rounded-sm bg-slate-900/60 border-slate-700/50 backdrop-blur-sm hover:border-slate-600/50 transition-all duration-300"
export const ADMIN_CARD_INTERACTIVE = "rounded-sm bg-slate-900/60 border-slate-700/50 backdrop-blur-sm hover:border-purple-500/30 hover:bg-slate-900/80 transition-all duration-300 cursor-pointer"
export const ADMIN_TAB_LIST = "bg-slate-800/60 backdrop-blur-sm p-1 rounded-sm border border-slate-700/30"
export const ADMIN_TAB_TRIGGER = "data-[state=active]:bg-gradient-to-r data-[state=active]:from-purple-600/80 data-[state=active]:to-blue-600/80 data-[state=active]:text-white data-[state=active]:shadow-lg data-[state=active]:shadow-purple-500/10 rounded-sm text-sm transition-all duration-200"
export const ADMIN_SECTION_SPACING = "space-y-6"
export const ADMIN_STAT_GRID = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"
export const ADMIN_CONTENT_GRID = "grid grid-cols-1 lg:grid-cols-2 gap-6"
export const ADMIN_ICON_BOX = "rounded-sm flex items-center justify-center backdrop-blur-sm"
export const ADMIN_PROGRESS_TRACK = "bg-slate-700/60 rounded-full h-2"
export const ADMIN_PROGRESS_FILL = "bg-gradient-to-r from-purple-500 to-blue-500 rounded-full h-2 transition-all duration-500"
export const ADMIN_PRIMARY_BTN = "bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white border-0 shadow-lg shadow-purple-500/20 hover:shadow-purple-500/30 transition-all duration-300"
export const ADMIN_OUTLINE_BTN = "border-slate-600/80 text-slate-300 hover:bg-slate-800/80 hover:border-slate-500/80 hover:text-white backdrop-blur-sm transition-all duration-200"
export const ADMIN_GLASS_SURFACE = "bg-white/[0.03] backdrop-blur-sm border border-white/[0.06]"
export const ADMIN_INPUT = "bg-slate-900/80 border-slate-700/60 text-white placeholder:text-slate-500 backdrop-blur-sm focus-visible:ring-purple-500/30 focus-visible:border-purple-500/30 transition-colors"
export const ADMIN_DIALOG = "bg-slate-950/95 border-slate-700/50 backdrop-blur-xl shadow-2xl"
