-- Helper: set Postgres settings so scheduled jobs can read app.settings.* (optional).
-- Usage (run once in SQL editor, customize values):
--   select set_config('app.settings.project_url', 'https://YOUR_PROJECT_REF.supabase.co', true);
--   select set_config('app.settings.service_role_key', 'YOUR_SUPABASE_SERVICE_ROLE_KEY', true);
--   select set_config('app.settings.cron_secret', 'LONG_RANDOM_VALUE', true);
